<?php
return array(
'AL' => array( // Albanian states.
		'AL-01' => 'Berat',
		'AL-09' => 'Dibër',
		'AL-02' => 'Durrsës',
		'AL-03' => 'Elbasan',
		'AL-04' => 'Fier',
		'AL-05' => 'Gjirokastër',
		'AL-06' => 'Korcë',
		'AL-07' => 'Kukës',
		'AL-08' => 'Lezhë',
		'AL-10' => 'Shkodër',
		'AL-11' => 'Tiranë',
		'AL-12' => 'Vlorë',
	),
'AO' => array( // Angolan states.
    'BGO' => 'Bengo',
    'BLU' => 'Benguela',
    'BIE' => 'Bie',
    'CAB' => 'Cabinda',
    'CNN' => 'Cunene',
    'HUA' => 'Huambo',
    'HUI' => 'Huila',
    'CCU' => 'Cuando-Cubango',
    'CNO' => 'Cuanza Norte',
    'CUS' => 'Cuanza Sul',
    'LUA' => 'Luanda',
    'LNO' => 'Lunda Norte',
    'LSU' => 'Lunda Sul',
    'MAL' => 'Malange',
    'MOX' => 'Moxico',
    'NAM' => 'Namibe',
    'UIG' => 'Uige',
    'ZAI' => 'Zaire',
),
'AR' => array( // Argentinian provinces.
    'C' => 'Capital federal',
    'B' => 'Buenos Aires',
    'K' => 'Catamarca',
    'H' => 'Chaco',
    'U' => 'Chubut',
    'X' => 'Cordoba',
    'W' => 'Corrientes',
    'E' => 'Entre Rios',
    'P' => 'Formosa',
    'Y' => 'Jujuy',
    'L' => 'La Pampa',
    'F' => 'La Rioja',
    'M' => 'Mendoza',
    'N' => 'Misiones',
    'Q' => 'Neuquen',
    'R' => 'Rio Negro',
    'A' => 'Salta',
    'J' => 'San Juan',
    'D' => 'San Luis',
    'Z' => 'Santa Cruz',
    'S' => 'Santa Fe',
    'G' => 'Santiago del Estero',
    'V' => 'Tierra del Fuego',
    'T' => 'Tucuman',
),
'AU' => array( // Australian states.
    'ACT' => 'Australian Capital Territory',
    'NSW' => 'New South Wales',
    'NT'  => 'Northern Territory',
    'QLD' => 'Queensland',
    'SA'  => 'South Australia',
    'TAS' => 'Tasmania',
    'VIC' => 'Victoria',
    'WA'  => 'Western Australia',
),
'BD' => array( // Bangladeshi districts.
    'BD-05' => 'Bagerhat zila',
    'BD-01' => 'Bandarban zila',
    'BD-02' => 'Barguna zila',
    'BD-06' => 'Barisal zila',
    'BD-07' => 'Bhola zila',
    'BD-03' => 'Bogra zila',
    'BD-04' => 'Brahmanbaria zila',
    'BD-09' => 'Chandpur zila',
    'BD-10' => 'Chittagong zila',
    'BD-12' => 'Chuadanga zila',
    'BD-11' => "Cox's Bazar zila",
    'BD-08' => 'Comilla zila',
    'BD-13' => 'Dhaka zila',
    'BD-14' => 'Dinajpur zila',
    'BD-15' => 'Faridpur zila',
    'BD-16' => 'Feni zila',
    'BD-19' => 'Gaibandha zila',
    'BD-18' => 'Gazipur zila',
    'BD-17' => 'Gopalganj zila',
    'BD-20' => 'Habiganj zila',
    'BD-21' => 'Jamalpur zila',
    'BD-22' => 'Jessore zila',
    'BD-25' => 'Jhalakati zila',
    'BD-23' => 'Jhenaidah zila',
    'BD-24' => 'Jaipurhat zila',
    'BD-29' => 'Khagrachari zila',
    'BD-27' => 'Khulna zila',
    'BD-26' => 'Kishorganj zila',
    'BD-28' => 'Kurigram zila',
    'BD-30' => 'Kushtia zila',
    'BD-31' => 'Lakshmipur zila',
    'BD-32' => 'Lalmonirhat zila',
    'BD-36' => 'Madaripur zila',
    'BD-37' => 'Magura zila',
    'BD-33' => 'Manikganj zila',
    'BD-39' => 'Meherpur zila',
    'BD-38' => 'Moulvibazar zila',
    'BD-35' => 'Munshiganj zila',
    'BD-34' => 'Mymensingh zila',
    'BD-48' => 'Naogaon zila',
    'BD-43' => 'Narail zila',
    'BD-40' => 'Narayanganj zila',
    'BD-42' => 'Narsingdi zila',
    'BD-44' => 'Natore zila',
    'BD-45' => 'Nawabganj zila',
    'BD-41' => 'Netrakona zila',
    'BD-46' => 'Nilphamari zila',
    'BD-47' => 'Noakhali zila',
    'BD-49' => 'Pabna zila',
    'BD-52' => 'Panchagarh zila',
    'BD-51' => 'Patuakhali zila',
    'BD-50' => 'Pirojpur zila',
    'BD-53' => 'Rajbari zila',
    'BD-54' => 'Rajshahi zila',
    'BD-56' => 'Rangamati zila',
    'BD-55' => 'Rangpur zila',
    'BD-58' => 'Satkhira zila',
    'BD-62' => 'Shariatpur zila',
    'BD-57' => 'Sherpur zila',
    'BD-59' => 'Sirajganj zila',
    'BD-61' => 'Sunamganj zila',
    'BD-60' => 'Sylhet zila',
    'BD-63' => 'Tangail zila',
    'BD-64' => 'Thakurgaon zila',
),
'BG' => array( // Bulgarian states.
    'BG-01' => 'Blagoevgrad',
    'BG-02' => 'Burgas',
    'BG-08' => 'Dobric',
    'BG-07' => 'Gabrovo',
    'BG-26' => 'Haskovo',
    'BG-09' => 'Kardzali',
    'BG-10' => 'Kjstendil',
    'BG-11' => 'Lovec',
    'BG-12' => 'Montana',
    'BG-13' => 'Pazardzik',
    'BG-14' => 'Pernik',
    'BG-15' => 'Pleven',
    'BG-16' => 'Plovdiv',
    'BG-17' => 'Razgrad',
    'BG-18' => 'Ruse',
    'BG-27' => 'Sumen',
    'BG-19' => 'Silistra',
    'BG-20' => 'Sliven',
    'BG-21' => 'Smoljan',
    'BG-23' => 'Sofia', // Sofia District is not in Mautic
    'BG-22' => 'Sofia',
    'BG-24' => 'Stara Zagora',
    'BG-25' => 'Targoviste',
    'BG-03' => 'Varna',
    'BG-04' => 'Veliko Tarnovo',
    'BG-05' => 'Vidin',
    'BG-06' => 'Vraca',
    'BG-28' => 'Jambol',
),
'BJ' => array( // Beninese states.
    'AL' => 'Alibori',
    'AK' => 'Atakora',
    'AQ' => 'Atlantique',
    'BO' => 'Borgou',
    'CO' => 'Collines',
    'KO' => 'Kouffo',
    'DO' => 'Donga',
    'LI' => 'Littoral',
    'MO' => 'Mono',
    'OU' => 'Oueme',
    'PL' => 'Plateau',
    'ZO' => 'Zou',
),
'BO' => array( // Bolivian states.
	'BO-B' => 'El Beni',
	'BO-H' => 'Chuquisaca',
	'BO-C' => 'Cochabamba',
	'BO-L' => 'La Paz',
	'BO-O' => 'Oruro',
	'BO-N' => 'Pando',
	'BO-P' => 'Potosi',
	'BO-S' => '', // Missing in Mautic
	'BO-T' => 'Tarija',
),
'BR' => array( // Brazilian states.
	'AC' => 'Acre',
	'AL' => 'Alagoas',
	'AP' => 'Amapa',
	'AM' => 'Amazonas',
	'BA' => 'Bahia',
	'CE' => 'Ceara',
	'DF' => 'Distrito Federal',
	'ES' => 'Espirito Santo',
	'GO' => 'Goias',
	'MA' => 'Maranhao',
	'MT' => 'Mato Grosso',
	'MS' => 'Mato Grosso do Sul',
	'MG' => 'Minas Gerais',
	'PA' => 'Para',
	'PB' => 'Paraiba',
	'PR' => 'Parana',
	'PE' => 'Pernambuco',
	'PI' => 'Piaui',
	'RJ' => 'Rio de Janeiro',
	'RN' => 'Rio Grande do Norte',
	'RS' => 'Rio Grande do Sul',
	'RO' => 'Rondonia',
	'RR' => 'Roraima',
	'SC' => 'Santa Catarina',
	'SP' => 'Sao Paulo',
	'SE' => 'Sergipe',
	'TO' => 'Tocantins',
),
'CA' => array( // Canadian states.
	'AB' => 'Alberta',
	'BC' => 'British Columbia',
	'MB' => 'Manitoba',
	'NB' => 'New Brunswick',
	'NL' => 'Newfoundland and Labrador',
	'NT' => 'Northwest Territories',
	'NS' => 'Nova Scotia',
	'NU' => 'Nunavut',
	'ON' => 'Ontario',
	'PE' => 'Prince Edward Island',
	'QC' => 'Quebec',
	'SK' => 'Saskatchewan',
	'YT' => 'Yukon Territory',
),
'CH' => array( // Swiss cantons.
	'AG' => 'Aargau',
	'AR' => 'Appenzell Ausserrhoden',
	'AI' => 'Appenzell Innerrhoden',
	'BL' => 'Basel-Landschaft',
	'BS' => 'Basel-Stadt',
	'BE' => 'Bern',
	'FR' => 'Fribourg',
	'GE' => 'Genève',
	'GL' => 'Glarus',
	'GR' => 'Graubünden',
	'JU' => 'Jura',
	'LU' => 'Luzern',
	'NE' => 'Neuchâtel',
	'NW' => 'Nidwalden',
	'OW' => 'Obwalden',
	'SH' => 'Schaffhausen',
	'SZ' => 'Schwyz',
	'SO' => 'Solothurn',
	'SG' => 'St. Gallen',
	'TG' => 'Thurgau',
	'TI' => 'Ticino',
	'UR' => 'Uri',
	'VS' => 'Valais',
	'VD' => 'Vaud',
	'ZG' => 'Zug',
	'ZH' => 'Zürich',
),
'CL' => array( // Chilean states.
	'CL-AI' => 'Aisen del General Carlos Ibanez del Campo',
	'CL-AN' => 'Antofagasta',
	'CL-AP' => '', // Missing in Mautic
	'CL-AR' => 'Araucania',
	'CL-AT' => 'Atacama',
	'CL-BI' => 'Bio-Bio',
	'CL-CO' => 'Coquimbo',
	'CL-LI' => 'Libertador General Bernardo O\'Higgins',
	'CL-LL' => 'Los Lagos',
	'CL-LR' => '', // Missing in Mautic
	'CL-MA' => 'Magallanes',
	'CL-ML' => 'Maule',
	'CL-NB' => '', // Missing in Mautic
	'CL-RM' => 'Region Metropolitana de Santiago',
	'CL-TA' => 'Tarapaca',
	'CL-VS' => 'Valparaiso',
),
'CN' => array( // Chinese states.
	'CN1'  => 'Yunnan',
	'CN2'  => 'Beijing',
	'CN3'  => 'Tianjin',
	'CN4'  => 'Hebei',
	'CN5'  => 'Shanxi',
	'CN6'  => 'Neia Mongol (mn)',
	'CN7'  => 'Liaoning',
	'CN8'  => 'Jilin',
	'CN9'  => 'Heilongjiang',
	'CN10' => 'Shanghai',
	'CN11' => 'Jiangsu',
	'CN12' => 'Zhejiang',
	'CN13' => 'Anhui',
	'CN14' => 'Fujian',
	'CN15' => 'Jiangxi',
	'CN16' => 'Shandong',
	'CN17' => 'Henan',
	'CN18' => 'Hubei',
	'CN19' => 'Hunan',
	'CN20' => 'Guangdong',
	'CN21' => 'Guangxi', // Adjusted to match "Guangxi" in Mautic
	'CN22' => 'Hainan',
	'CN23' => 'Chongqing',
	'CN24' => 'Sichuan',
	'CN25' => 'Guizhou',
	'CN26' => 'Shaanxi',
	'CN27' => 'Gansu',
	'CN28' => 'Qinghai',
	'CN29' => '', // Missing in Mautic
	'CN30' => 'Macau', // Adjusted to match "Macau" in Mautic
	'CN31' => 'Xizang', // Adjusted to match "Xizang" in Mautic
	'CN32' => 'Xinjiang',
),
'CO' => array( // Colombian states.
	'CO-AMA' => 'Amazonea', // Adjusted to match "Amazonea" in Mautic
	'CO-ANT' => 'Antioquia',
	'CO-ARA' => 'Arauca',
	'CO-ATL' => 'Atlántico',
	'CO-BOL' => 'Bolívar',
	'CO-BOY' => 'Boyacá',
	'CO-CAL' => 'Caldea', // Adjusted to match "Caldea" in Mautic
	'CO-CAQ' => 'Caquetá',
	'CO-CAS' => 'Casanare',
	'CO-CAU' => 'Cauca',
	'CO-CES' => 'Cesar',
	'CO-CHO' => 'Chocó',
	'CO-COR' => 'Córdoba',
	'CO-CUN' => 'Cundinamarca',
	'CO-DC' => 'Distrito Capital de Bogotá', // Adjusted to match "Distrito Capital de Bogotá" in Mautic
	'CO-GUA' => 'Guainía',
	'CO-GUV' => 'Guaviare',
	'CO-HUI' => '', // Missing in Mautic
	'CO-LAG' => 'La Guajira',
	'CO-MAG' => 'Magdalena',
	'CO-MET' => 'Meta',
	'CO-NAR' => 'Nariño',
	'CO-NSA' => 'Norte de Santander',
	'CO-PUT' => 'Putumayo',
	'CO-QUI' => 'Quindio', // Adjusted to match "Quindio" in Mautic
	'CO-RIS' => 'Risaralda',
	'CO-SAN' => 'Santander',
	'CO-SAP' => 'San Andrés, Providencia y Santa Catalina', // Adjusted to match "San Andrés, Providencia y Santa Catalina" in Mautic
	'CO-SUC' => 'Sucre',
	'CO-TOL' => 'Tolima',
	'CO-VAC' => 'Valle del Cauca',
	'CO-VAU' => 'Vaupés',
	'CO-VID' => 'Vichada',
),
'CR' => array( // Costa Rican states.
	'CR-A' => 'Alajuela',
	'CR-C' => 'Cartago',
	'CR-G' => 'Guanacaste',
	'CR-H' => 'Heredia',
	'CR-L' => 'Limon', // Adjusted to match "Limon" in Mautic
	'CR-P' => 'Puntarenas',
	'CR-SJ' => 'San Jose', // Adjusted to match "San Jose" in Mautic
),
'DE' => array( // German states.
	'DE-BW' => 'Baden-Württemberg',
	'DE-BY' => 'Bayern', // Adjusted to match "Bayern" in Mautic
	'DE-BE' => 'Berlin',
	'DE-BB' => 'Brandenburg',
	'DE-HB' => 'Bremen',
	'DE-HH' => 'Hamburg',
	'DE-HE' => 'Hessen', // Adjusted to match "Hessen" in Mautic
	'DE-MV' => 'Mecklenburg-Vorpommern',
	'DE-NI' => 'Niedersachsen', // Adjusted to match "Niedersachsen" in Mautic
	'DE-NW' => 'Nordrhein-Westfalen', // Adjusted to match "Nordrhein-Westfalen" in Mautic
	'DE-RP' => 'Rheinland-Pfalz', // Adjusted to match "Rheinland-Pfalz" in Mautic
	'DE-SL' => 'Saarland',
	'DE-SN' => 'Sachsen', // Adjusted to match "Sachsen" in Mautic
	'DE-ST' => 'Sachsen-Anhalt', // Adjusted to match "Sachsen-Anhalt" in Mautic
	'DE-SH' => 'Schleswig-Holstein',
	'DE-TH' => 'Thüringen', // Adjusted to match "Thüringen" in Mautic
),
'DO' => array( // Dominican states.
	'DO-01' => 'Distrito Nacional (Santo Domingo)', // Adjusted to match Mautic
	'DO-02' => 'Azua',
	'DO-03' => 'Bahoruco', // Adjusted to match Mautic
	'DO-04' => 'Barahona',
	'DO-05' => 'Dajabón', // Adjusted to match Mautic
	'DO-06' => 'Duarte',
	'DO-08' => 'El Seybo [El Seibo]', // Adjusted to match Mautic
	'DO-09' => 'Espaillat',
	'DO-30' => 'Hato Mayor',
	'DO-10' => 'Independencia',
	'DO-11' => 'La Altagracia',
	'DO-07' => 'La Estrelleta [Elias Pina]', // Adjusted to match Mautic
	'DO-12' => 'La Romana',
	'DO-13' => 'La Vega',
	'DO-14' => 'Maroia Trinidad Sánchez', // Adjusted to match Mautic
	'DO-28' => 'Monseñor Nouel',
	'DO-15' => 'Monte Cristi',
	'DO-29' => 'Monte Plata',
	'DO-16' => 'Pedernales',
	'DO-17' => 'Peravia',
	'DO-18' => 'Puerto Plata',
	'DO-20' => 'Samaná', // Adjusted to match Mautic
	'DO-21' => 'San Cristóbal',
	'DO-23' => 'San Pedro de Macorís',
	'DO-24' => 'Sánchez Ramírez',
	'DO-25' => 'Santiago',
	'DO-26' => 'Santiago Rodríguez',
	'DO-27' => 'Valverde',
	'DO-19' => 'Salcedo', // Added Salcedo from Mautic
	// The following entries do not have matches in Mautic, so they are left blank:
	'DO-33' => '',
	'DO-34' => '',
	'DO-35' => '',
	'DO-36' => '',
	'DO-37' => '',
	'DO-38' => '',
	'DO-39' => '',
	'DO-22' => '',
	'DO-31' => '',
	'DO-32' => '',
	'DO-40' => '',
	'DO-41' => '',
	'DO-42' => '',
),
'DZ' => array( // Algerian states.
	'DZ-01' => 'Adrar',
	'DZ-02' => 'Chlef',
	'DZ-03' => 'Laghouat',
	'DZ-04' => 'Oum el Bouaghi', // Adjusted to match Mautic
	'DZ-05' => 'Batna',
	'DZ-06' => 'Bejaia', // Adjusted to match Mautic
	'DZ-07' => 'Biskra',
	'DZ-08' => 'Bechar', // Adjusted to match Mautic
	'DZ-09' => 'Blida',
	'DZ-10' => 'Bouira',
	'DZ-11' => 'Tamanghasset', // Adjusted to match Mautic
	'DZ-12' => 'Tebessa', // Adjusted to match Mautic
	'DZ-13' => 'Tlemcen',
	'DZ-14' => 'Tiaret',
	'DZ-15' => 'Tizi Ouzou',
	'DZ-16' => 'Alger', // Adjusted to match Mautic
	'DZ-17' => 'Djelfa',
	'DZ-18' => 'Jijel',
	'DZ-19' => 'Setif', // Adjusted to match Mautic
	'DZ-20' => 'Saida', // Adjusted to match Mautic
	'DZ-21' => 'Skikda',
	'DZ-22' => 'Sidi Bel Abbes', // Adjusted to match Mautic
	'DZ-23' => 'Annaba',
	'DZ-24' => 'Guelma',
	'DZ-25' => 'Constantine',
	'DZ-26' => 'Medea', // Adjusted to match Mautic
	'DZ-27' => 'Mostaganem',
	'DZ-28' => 'Msila', // Adjusted to match Mautic
	'DZ-29' => 'Mascara',
	'DZ-30' => 'Ouargla',
	'DZ-31' => 'Oran',
	'DZ-32' => 'El Bayadh',
	'DZ-33' => 'Illizi',
	'DZ-34' => 'Bordj Bou Arreridj', // Adjusted to match Mautic
	'DZ-35' => 'Boumerdes', // Adjusted to match Mautic
	'DZ-36' => 'El Tarf',
	'DZ-37' => 'Tindouf',
	'DZ-38' => 'Tissemsilt',
	'DZ-39' => 'El Oued',
	'DZ-40' => 'Khenchela', // Adjusted to match Mautic
	'DZ-41' => 'Souk Ahras',
	'DZ-42' => 'Tipaza', // Adjusted to match Mautic
	'DZ-43' => 'Mila',
	'DZ-44' => 'Ain Defla', // Adjusted to match Mautic
	'DZ-45' => 'Naama',
	'DZ-46' => 'Ain Tmouchent', // Adjusted to match Mautic
	'DZ-47' => 'Ghardaia', // Adjusted to match Mautic
	'DZ-48' => 'Relizane',
),
'EC' => array( // Ecuadorian states.
    'EC-A' => 'Azuay',
    'EC-B' => 'Bolivar',
    'EC-F' => 'Canar',
    'EC-C' => 'Carchi',
    'EC-H' => 'Chimborazo',
    'EC-X' => 'Cotopaxi',
    'EC-O' => 'El Oro',
    'EC-E' => 'Esmeraldas',
    'EC-W' => 'Galapagos',
    'EC-G' => 'Guayas',
    'EC-I' => 'Imbabura',
    'EC-L' => 'Loja',
    'EC-R' => 'Los Rios',
    'EC-M' => 'Manabi',
    'EC-S' => 'Morona-Santiago',
    'EC-N' => 'Napo',
    'EC-D' => 'Orellana',
    'EC-Y' => 'Pastaza',
    'EC-P' => 'Pichincha',
    'EC-SE' => '',
    'EC-SD' => '',
    'EC-U' => 'Sucumbios',
    'EC-T' => 'Tungurahua',
    'EC-Z' => 'Zamora-Chinchipe',
),
'EG' => array( // Egyptian states.
    'EGALX' => 'Al Iskandarlyah',
    'EGASN' => 'Aswan',
    'EGAST' => 'Asyut',
    'EGBA'  => 'Al Bahr al Ahmar',
    'EGBH'  => 'Al Buhayrah',
    'EGBNS' => 'Bani Suwayf',
    'EGC'   => 'Al Qahirah',
    'EGDK'  => 'Ad Daqahllyah',
    'EGDT'  => 'Dumyat',
    'EGFYM' => 'Al Fayym',
    'EGGH'  => 'Al Gharbiyah',
    'EGGZ'  => 'Al Jizah',
    'EGIS'  => 'Al Isma illyah',
    'EGJS'  => 'Janub Sina\'',
    'EGKB'  => 'Al Qalyublyah',
    'EGKFS' => 'Kafr ash Shaykh',
    'EGKN'  => 'Qina',
    'EGLX'  => '',
    'EGMN'  => 'Al Minya',
    'EGMNF' => 'Al Minuflyah',
    'EGMT'  => 'Matruh',
    'EGPTS' => 'Bur Sa\'id',
    'EGSHG' => 'Suhaj',
    'EGSHR' => 'Ash Sharqiyah',
    'EGSIN' => 'Shamal Sina\'',
    'EGSUZ' => 'As Suways',
    'EGWAD' => 'Al Wadi al Jadid',
),
'ES' => array( // Spanish states.
    'C'  => 'La Coruña',
    'VI' => 'Álava',
    'AB' => 'Albacete',
    'A'  => 'Alicante',
    'AL' => 'Almería',
    'O'  => 'Asturias',
    'AV' => 'Ávila',
    'BA' => 'Badajoz',
    'PM' => 'Baleares',
    'B'  => 'Barcelona',
    'BU' => 'Burgos',
    'CC' => 'Cáceres',
    'CA' => 'Cádiz',
    'S'  => 'Cantabria',
    'CS' => 'Castellón',
    'CE' => 'Ceuta',
    'CR' => 'Ciudad Real',
    'CO' => 'Córdoba',
    'CU' => 'Cuenca',
    'GI' => 'Girona [Gerona]',
    'GR' => 'Granada',
    'GU' => 'Guadalajara',
    'SS' => 'Guipúzcoa',
    'H'  => 'Huelva',
    'HU' => 'Huesca',
    'J'  => 'Jaén',
    'LO' => 'La Rioja',
    'GC' => 'Las Palmas',
    'LE' => 'León',
    'L'  => 'Lleida [Lérida]',
    'LU' => 'Lugo',
    'M'  => 'Madrid',
    'MA' => 'Málaga',
    'ML' => 'Melilla',
    'MU' => 'Murcia',
    'NA' => 'Navarra',
    'OR' => 'Ourense',
    'P'  => 'Palencia',
    'PO' => 'Pontevedra',
    'SA' => 'Salamanca',
    'TF' => 'Santa Cruz de Tenerife',
    'SG' => 'Segovia',
    'SE' => 'Sevilla',
    'SO' => 'Soria',
    'T'  => 'Tarragona',
    'TE' => 'Teruel',
    'TO' => 'Toledo',
    'V'  => 'Valencia',
    'VA' => 'Valladolid',
    'BI' => 'Vizcaya',
    'ZA' => 'Zamora',
    'Z'  => 'Zaragoza',
),
'GH' => array( // Ghanaian regions.
    'AF' => '',
    'AH' => 'Ashanti',
    'BA' => 'Brong-Ahafo',
    'BO' => '',
    'BE' => '',
    'CP' => '',
    'EP' => '',
    'AA' => 'Greater Accra',
    'NE' => '',
    'NP' => '',
    'OT' => '',
    'SV' => '',
    'UE' => 'Upper East',
    'UW' => 'Upper West',
    'TV' => 'Volta',
    'WP' => '',
    'WN' => '',
),
'GR' => array( // Greek regions.
    'I' => 'Attiki',
    'A' => '',
    'B' => '',
    'C' => '',
    'D' => '',
    'E' => '',
    'F' => '',
    'G' => '',
    'H' => '',
    'J' => '',
    'K' => '',
    'L' => 'Kyklades',
    'M' => 'Irakleion',
),
'GT' => array( // Guatemalan states.
    'GT-AV' => 'Alta Verapez',
    'GT-BV' => 'Baja Verapez',
    'GT-CM' => 'Chimaltenango',
    'GT-CQ' => 'Chiquimula',
    'GT-PR' => 'El Progreso',
    'GT-ES' => 'Escuintla',
    'GT-GU' => 'Guatemala',
    'GT-HU' => 'Huehuetenango',
    'GT-IZ' => 'Izabal',
    'GT-JA' => 'Jalapa',
    'GT-JU' => 'Jutiapa',
    'GT-PE' => 'Peten',
    'GT-QZ' => 'Quetzaltenango',
    'GT-QC' => 'Quiche',
    'GT-RE' => 'Reta.thuleu',
    'GT-SA' => 'Sacatepequez',
    'GT-SM' => 'San Marcos',
    'GT-SR' => 'Santa Rosa',
    'GT-SO' => 'Solol6',
    'GT-SU' => 'Suchitepequez',
    'GT-TO' => 'Totonicapan',
    'GT-ZA' => 'Zacapa',
),
'HK' => array( // Hong Kong states.
    'HONG KONG'       => 'Islands', // Matched with 'Islands' in Mautic
    'KOWLOON'         => 'Kowloon City',
    'NEW TERRITORIES' => '',
),
'HN' => array( // Honduran states.
    'HN-AT' => 'Atlantida',
    'HN-IB' => 'Islas de la Bahia',
    'HN-CH' => 'Choluteca',
    'HN-CL' => 'Colon',
    'HN-CM' => 'Comayagua',
    'HN-CP' => 'Copan',
    'HN-CR' => 'Cortes',
    'HN-EP' => 'El Paraiso',
    'HN-FM' => 'Francisco Morazan',
    'HN-GD' => 'Gracias a Dios',
    'HN-IN' => 'Intibuca',
    'HN-LE' => 'Lempira',
    'HN-LP' => 'La Paz',
    'HN-OC' => 'Ocotepeque',
    'HN-OL' => 'Olancho',
    'HN-SB' => 'Santa Barbara',
    'HN-VA' => 'Valle',
    'HN-YO' => 'Yoro',
),
'HU' => array( // Hungarian states.
    'BK' => 'Bács-Kiskun',
    'BE' => 'Békés',
    'BA' => 'Baranya',
    'BZ' => 'Borsod-Abaúj-Zemplén',
    'BU' => 'Budapest',
    'CS' => 'Csongrád',
    'FE' => 'Fejér',
    'GS' => 'Győr-Moson-Sopron',
    'HB' => 'Hajdú-Bihar',
    'HE' => 'Heves',
    'JN' => 'Jász-Nagykun-Szolnok',
    'KE' => 'Komárom-Esztergom',
    'NO' => 'Nógrád',
    'PE' => 'Pest',
    'SO' => 'Somogy',
    'SZ' => 'Szabolcs-Szatmár-Bereg',
    'TO' => 'Tolna',
    'VA' => 'Vas',
    'VE' => 'Veszprém',
    'ZA' => 'Zala',
),
'ID' => array( // Indonesian provinces.
    'AC' => 'Aceh', // Changed from 'Daerah Istimewa Aceh'
    'SU' => 'Sumatera Utara',
    'SB' => 'Sumatra Barat', // Changed from 'Sumatera Barat'
    'RI' => 'Riau',
    'KR' => 'Kepulauan Riau',
    'JA' => 'Jambi',
    'SS' => 'Sumatra Selatan', // Changed from 'Sumatera Selatan'
    'BB' => 'Bangka Belitung',
    'BE' => 'Bengkulu',
    'LA' => 'Lampung',
    'JK' => 'Jakarta Raya', // Changed from 'DKI Jakarta'
    'JB' => 'Jawa Barat',
    'BT' => 'Banten',
    'JT' => 'Jawa Tengah',
    'JI' => 'Jawa Timur',
    'YO' => 'Yogyakarta', // Changed from 'Daerah Istimewa Yogyakarta'
    'BA' => 'Bali',
    'NB' => 'Nusa Tenggara Barat',
    'NT' => 'Nusa Tenggara Timur',
    'KB' => 'Kalimantan Barat',
    'KT' => 'Kalimantan Tengah',
    'KI' => 'Kalimantan Timur',
    'KS' => 'Kalimantan Selatan',
    'KU' => 'Kalimantan Utara',
    'SA' => 'Sulawesi Utara',
    'ST' => 'Sulawesi Tengah',
    'SG' => 'Sulawesi Tenggara',
    'SR' => 'Sulawesi Barat',
    'SN' => 'Sulawesi Selatan',
    'GO' => 'Gorontalo',
    'MA' => 'Maluku',
    'MU' => 'Maluku Utara',
    'PA' => 'Papua',
    'PB' => 'Papua Barat',
),
'IE' => array( // Irish states.
    'CW' => 'Carlow',
    'CN' => 'Cavan',
    'CE' => 'Clare',
    'CO' => 'Cork',
    'DL' => 'Donegal',
    'D'  => 'Dublin',
    'G'  => 'Galway',
    'KY' => 'Kerry',
    'KE' => 'Kildare',
    'KK' => 'Kilkenny',
    'LS' => 'Laois',
    'LM' => 'Leitrim',
    'LK' => 'Limerick',
    'LD' => 'Longford',
    'LH' => 'Louth',
    'MO' => 'Mayo',
    'MH' => 'Meath',
    'MN' => 'Monaghan',
    'OY' => 'Offaly',
    'RN' => 'Roscommon',
    'SO' => 'Sligo',
    'TA' => 'Tipperary',
    'WD' => 'Waterford',
    'WH' => 'Westmeath',
    'WX' => 'Wexford',
    'WW' => 'Wicklow',
),
'IN' => array(  //India
    'AP' => 'Andhra Pradesh',                // No change needed
    'AR' => 'Arunachal Pradesh',             // No change needed
    'AS' => 'Assam',                         // No change needed
    'BR' => 'Bihar',                         // No change needed
    'CT' => 'Chhattisgarh',                  // No change needed
    'GA' => 'Goa',                           // No change needed
    'GJ' => 'Gujarat',                       // No change needed
    'HR' => 'Haryana',                       // No change needed
    'HP' => 'Himachal Pradesh',              // No change needed
    'JK' => 'Jammu and Kashmir',             // No change needed
    'JH' => 'Jharkhand',                     // No change needed
    'KA' => 'Karnataka',                     // No change needed
    'KL' => 'Kerala',                        // No change needed
    'LA' => 'Lakshadweep',                   // Change from 'Ladakh' to 'Lakshadweep'
    'MP' => 'Madhya Pradesh',                // No change needed
    'MH' => 'Maharashtra',                   // No change needed
    'MN' => 'Manipur',                       // No change needed
    'ML' => 'Meghalaya',                     // No change needed
    'MZ' => 'Mizoram',                       // No change needed
    'NL' => 'Nagaland',       
    'OR' => 'Orissa',                        // Change from 'Odisha' to 'Orissa'
    'PB' => 'Punjab',                        // No change needed
    'RJ' => 'Rajasthan',                     // No change needed
    'SK' => 'Sikkim',                        // No change needed
    'TN' => 'Tamil Nadu',                    // No change needed
    'TS' => 'Telangana',                     // No change needed
    'TR' => 'Tripura',                       // No change needed
    'UK' => 'Uttarakhand',                   // No change needed
    'UP' => 'Uttar Pradesh',                 // No change needed
    'WB' => 'West Bengal',                   // No change needed
    'AN' => 'Andaman and Nicobar Islands',   // No change needed
    'CH' => 'Chandigarh',                    // No change needed
    'DN' => 'Dadra and Nagar Haveli',        // No change needed
    'DD' => 'Daman and Diu',                 // No change needed
    'DL' => 'Delhi',                         // No change needed
    'LD' => 'Lakshadweep',                   // Change from 'Lakshadeep' to 'Lakshadweep'
    'PY' => 'Pondicherry',                   // Change from 'Pondicherry (Puducherry)' to 'Pondicherry'
),
'IR' => array(  //Iran
    'KHZ' => 'Khuzestan',                              // No change needed
    'THR' => 'Tehran',                                 // No change needed
    'ILM' => 'Iliam',                                  // Change from 'Ilaam' to 'Iliam'
    'BHR' => 'Bushehr',                                // No change needed
    'ADL' => 'Ardabil',                                // No change needed
    'ESF' => 'Esfahan',                                // Change from 'Isfahan' to 'Esfahan'
    'YZD' => 'Yazd',                                   // No change needed
    'KRH' => 'Kermanshah',                             // No change needed
    'KRN' => 'Kerman',                                 // No change needed
    'HDN' => 'Hamadan',                                // No change needed
    'GZN' => 'Qazvin',                                 // Change from 'Ghazvin' to 'Qazvin'
    'ZJN' => 'Zanjan',                                 // No change needed
    'LRS' => 'Lorestan',                               // Change from 'Luristan' to 'Lorestan'
    'ABZ' => 'Alborz',                                 // No change needed
    'EAZ' => 'Azarbayjan-e Sharqi',                        // Change from 'East Azarbaijan (آذربایجان شرقی)' to 'Azarbayjan-e Sharqi'
    'WAZ' => 'Azarbayjan-e Gharbi',                        // Change from 'West Azarbaijan (آذربایجان غربی)' to 'Azarbayjan-e Gharbi'
    'CHB' => 'Chahar Mahall va Bakhtiari',             // Change from 'Chaharmahal and Bakhtiari (چهارمحال و بختیاری)' to 'Chahar Mahall va Bakhtiari'
    'SKH' => 'Khorasan',                         // Change from 'South Khorasan (خراسان جنوبی)' to 'Khorasan'
    'RKH' => 'Khorasan',                        // Change from 'Razavi Khorasan (خراسان رضوی)' to 'Khorasan'
    'NKH' => 'Khorasan',                         // Change from 'North Khorasan (خراسان شمالی)' to 'Khorasan'
    'SMN' => 'Semnan',                                 // No change needed
    'FRS' => 'Fars',                                   // No change needed
    'QHM' => 'Qom',                                    // No change needed
    'KRD' => 'Kordestan',                              // Change from 'Kurdistan / کردستان)' to 'Kordestan'
    'KBD' => 'Kohgiluyeh va Buyer Ahmad',              // Change from 'Kohgiluyeh and BoyerAhmad (کهگیلوییه و بویراحمد)' to 'Kohgiluyeh va Buyer Ahmad'
    'GLS' => 'Golestan',                               // No change needed
    'GIL' => 'Gilan',                                  // No change needed
    'MZN' => 'Mazandaran',                             // No change needed
    'MKZ' => 'Markazi',                                // Change from 'Markazi (مرکزی)' to 'Markazi'
    'HRZ' => 'Hormozgan',                              // Change from 'Hormozgan (هرمزگان)' to 'Hormozgan'
    'SBN' => 'Sistan va Baluchestan',                  // Change from 'Sistan and Baluchestan (سیستان و بلوچستان)' to 'Sistan va Baluchestan'
),
'IT' => array(  //Italy
    'AG' => 'Agrigento',                                // No change needed
    'AL' => 'Alessandria',                              // No change needed
    'AN' => 'Ancona',                                   // No change needed
    'AO' => 'Aosta',                                    // No change needed
    'AR' => 'Arezzo',                                   // No change needed
    'AP' => 'Ascoli Piceno',                            // No change needed
    'AT' => 'Asti',                                     // No change needed
    'AV' => 'Avellino',                                 // No change needed
    'BA' => 'Bari',                                     // No change needed
    'BT' => 'Barletta-Andria-Trani',                    // Change from 'Barletta-Andria-Trani' to 'Barletta-Andria-Trani'
    'BL' => 'Belluno',                                  // No change needed
    'BN' => 'Benevento',                                // No change needed
    'BG' => 'Bergamo',                                  // No change needed
    'BI' => 'Biella',                                   // No change needed
    'BO' => 'Bologna',                                  // No change needed
    'BZ' => 'Bolzano',                                  // No change needed
    'BS' => 'Brescia',                                  // No change needed
    'BR' => 'Brindisi',                                 // No change needed
    'CA' => 'Cagliari',                                 // No change needed
    'CL' => 'Caltanissetta',                            // No change needed
    'CB' => 'Campobasso',                               // No change needed
    'CE' => 'Caserta',                                  // No change needed
    'CT' => 'Catania',                                  // No change needed
    'CZ' => 'Catanzaro',                                // No change needed
    'CH' => 'Chieti',                                   // No change needed
    'CO' => 'Como',                                     // No change needed
    'CS' => 'Cosenza',                                  // No change needed
    'CR' => 'Cremona',                                  // No change needed
    'KR' => 'Crotone',                                  // No change needed
    'CN' => 'Cuneo',                                    // No change needed
    'EN' => 'Enna',                                     // No change needed
    'FM' => 'Fermo',                                    // No change needed
    'FE' => 'Ferrara',                                  // No change needed
    'FI' => 'Firenze',                                  // Change from 'Firenze' to 'Firenze'
    'FG' => 'Foggia',                                   // No change needed
    'FC' => 'Forlì-Cesena',                             // Change from 'Forlì-Cesena' to 'Forlì-Cesena'
    'FR' => 'Frosinone',                                // No change needed
    'GE' => 'Genova',                                   // No change needed
    'GO' => 'Gorizia',                                  // No change needed
    'GR' => 'Grosseto',                                 // No change needed
    'IM' => 'Imperia',                                  // No change needed
    'IS' => 'Isernia',                                  // No change needed
    'SP' => 'La Spezia',                                // No change needed
    'AQ' => "L'Aquila",                                 // No change needed
    'LT' => 'Latina',                                   // No change needed
    'LE' => 'Lecce',                                    // No change needed
    'LC' => 'Lecco',                                    // No change needed
    'LI' => 'Livorno',                                  // No change needed
    'LO' => 'Lodi',                                     // No change needed
    'LU' => 'Lucca',                                    // No change needed
    'MC' => 'Macerata',                                 // No change needed
    'MN' => 'Mantova',                                  // No change needed
    'MS' => 'Massa-Carrara',                            // No change needed
    'MT' => 'Matera',                                   // No change needed
    'ME' => 'Messina',                                  // No change needed
    'MI' => 'Milano',                                   // No change needed
    'MO' => 'Modena',                                   // No change needed
    'MB' => 'Monza e Brianza',                    // Change from 'Monza e della Brianza' to 'Monza e Brianza'
    'NA' => 'Napoli',                                   // No change needed
    'NO' => 'Novara',                                   // No change needed
    'NU' => 'Nuoro',                                    // No change needed
    'OR' => 'Oristano',                                 // No change needed
    'PD' => 'Padova',                                   // No change needed
    'PA' => 'Palermo',                                  // No change needed
    'PR' => 'Parma',                                    // No change needed
    'PV' => 'Pavia',                                    // No change needed
    'PG' => 'Perugia',                                  // No change needed
    'PU' => 'Pesaro e Urbino',                          // No change needed
    'PE' => 'Pescara',                                  // No change needed
    'PC' => 'Piacenza',                                 // No change needed
    'PI' => 'Pisa',                                     // No change needed
    'PT' => 'Pistoia',                                  // No change needed
    'PN' => 'Pordenone',                                // No change needed
    'PZ' => 'Potenza',                                  // No change needed
    'PO' => 'Prato',                                    // No change needed
    'RG' => 'Ragusa',                                   // No change needed
    'RA' => 'Ravenna',                                  // No change needed
    'RC' => 'Reggio Calabria',                          // No change needed
    'RE' => 'Reggio Emilia',                            // No change needed
    'RI' => 'Rieti',                                    // No change needed
    'RN' => 'Rimini',                                   // No change needed
    'RM' => 'Roma',                                     // No change needed
    'RO' => 'Rovigo',                                   // No change needed
    'SA' => 'Salerno',                                  // No change needed
    'SS' => 'Sassari',                                  // No change needed
    'SV' => 'Savona',                                   // No change needed
    'SI' => 'Siena',                                    // No change needed
    'SR' => 'Siracusa',                                 // No change needed
    'SO' => 'Sondrio',                                  // No change needed
    'SU' => 'Sud Sardegna',                             // No change needed
    'TA' => 'Taranto',                                  // No change needed
    'TE' => 'Teramo',                                   // No change needed
    'TR' => 'Terni',                                    // No change needed
    'TO' => 'Torino',                                   // No change needed
    'TP' => 'Trapani',                                  // No change needed
    'TN' => 'Trento',                                   // No change needed
    'TV' => 'Treviso',                                  // No change needed
    'TS' => 'Trieste',                                  // No change needed
    'UD' => 'Udine',                                    // No change needed
    'VA' => 'Varese',                                   // No change needed
    'VE' => 'Venezia',                                  // No change needed
    'VB' => 'Verbano-Cusio-Ossola',                     // No change needed
    'VC' => 'Vercelli',                                 // No change needed
    'VR' => 'Verona',                                   // No change needed
    'VV' => 'Vibo Valentia',                            // No change needed
    'VI' => 'Vicenza',                                  // No change needed
    'VT' => 'Viterbo',                                  // No change needed
),
'JM' => array( //Jamaica
    'JM-01' => 'Kingston',              // No change needed
    'JM-02' => 'Saint Andrew',          // No change needed
    'JM-03' => 'Saint Thomas',          // No change needed
    'JM-04' => 'Portland',              // No change needed
    'JM-05' => 'Saint Mary',            // No change needed
    'JM-06' => 'Saint Ann',             // No change needed
    'JM-07' => 'Trelawny',              // No change needed
    'JM-08' => 'Saint James',           // No change needed
    'JM-09' => 'Hanover',               // No change needed
    'JM-10' => 'Westmoreland',          // No change needed
    'JM-11' => 'Saint Elizabeth',       // No change needed
    'JM-12' => 'Manchester',            // No change needed
    'JM-13' => 'Clarendon',             // No change needed
    'JM-14' => 'Saint Catherine',       // No change needed
),
'JP' => array( //Japan
    'JP01' => 'Hokkaido',             // No change needed
    'JP02' => 'Aomori',               // No change needed
    'JP03' => 'Iwate',                // No change needed
    'JP04' => 'Miyagi',               // No change needed
    'JP05' => 'Akita',                // No change needed
    'JP06' => 'Yamagata',             // No change needed
    'JP07' => 'Fukushima',            // No change needed
    'JP08' => 'Ibaraki',              // No change needed
    'JP09' => 'Tochigi',              // No change needed
    'JP10' => 'Gunma',                // No change needed
    'JP11' => 'Saitama',              // No change needed
    'JP12' => 'Chiba',                // No change needed
    'JP13' => 'Tokyo',                // No change needed
    'JP14' => 'Kanagawa',             // No change needed
    'JP15' => 'Niigata',              // No change needed
    'JP16' => 'Toyama',               // No change needed
    'JP17' => 'Ishikawa',             // No change needed
    'JP18' => 'Fukui',                // No change needed
    'JP19' => 'Yamanashi',            // No change needed
    'JP20' => 'Nagano',               // No change needed
    'JP21' => 'Gifu',                 // No change needed
    'JP22' => 'Shizuoka',             // No change needed
    'JP23' => 'Aichi',                // No change needed
    'JP24' => 'Mie',                  // No change needed
    'JP25' => 'Shiga',                // No change needed
    'JP26' => 'Kyoto',                // No change needed
    'JP27' => 'Osaka',                // No change needed
    'JP28' => 'Hyogo',                // No change needed
    'JP29' => 'Nara',                 // No change needed
    'JP30' => 'Wakayama',             // No change needed
    'JP31' => 'Tottori',              // No change needed
    'JP32' => 'Shimane',              // No change needed
    'JP33' => 'Okayama',              // No change needed
    'JP34' => 'Hiroshima',            // No change needed
    'JP35' => 'Yamaguchi',            // No change needed
    'JP36' => 'Tokushima',            // No change needed
    'JP37' => 'Kagawa',               // No change needed
    'JP38' => 'Ehime',                // No change needed
    'JP39' => 'Kochi',                // No change needed
    'JP40' => 'Fukuoka',              // No change needed
    'JP41' => 'Saga',                 // No change needed
    'JP42' => 'Nagasaki',             // No change needed
    'JP43' => 'Kumamoto',             // No change needed
    'JP44' => 'Oita',                 // No change needed
    'JP45' => 'Miyazaki',             // No change needed
    'JP46' => 'Kagoshima',            // No change needed
    'JP47' => 'Okinawa',              // No change needed
),
'KE' => array( // Kenyan counties.
    'KE01' => 'Baringo County',             // Changed from 'Baringo'
    'KE02' => 'Bomet County',               // Changed from 'Bomet'
    'KE03' => 'Bungoma County',             // Changed from 'Bungoma'
    'KE04' => 'Busia County',               // Changed from 'Busia'
    'KE05' => 'Elgeyo-Marakwet County',     // Changed from 'Elgeyo-Marakwet'
    'KE06' => 'Embu County',                // Changed from 'Embu'
    'KE07' => 'Garissa County',             // Changed from 'Garissa'
    'KE08' => 'Homa Bay County',            // Changed from 'Homa Bay'
    'KE09' => 'Isiolo County',              // Changed from 'Isiolo'
    'KE10' => 'Kajiado County',             // Changed from 'Kajiado'
    'KE11' => 'Kakamega County',            // Changed from 'Kakamega'
    'KE12' => 'Kericho County',             // Changed from 'Kericho'
    'KE13' => 'Kiambu County',              // Changed from 'Kiambu'
    'KE14' => 'Kilifi County',              // Changed from 'Kilifi'
    'KE15' => 'Kirinyaga County',           // Changed from 'Kirinyaga'
    'KE16' => 'Kisii County',               // Changed from 'Kisii'
    'KE17' => 'Kisumu County',              // Changed from 'Kisumu'
    'KE18' => 'Kitui County',               // Changed from 'Kitui'
    'KE19' => 'Kwale County',               // Changed from 'Kwale'
    'KE20' => 'Laikipia County',            // Changed from 'Laikipia'
    'KE21' => 'Lamu County',                // Changed from 'Lamu'
    'KE22' => 'Machakos County',            // Changed from 'Machakos'
    'KE23' => 'Makueni County',             // Changed from 'Makueni'
    'KE24' => 'Mandera County',             // Changed from 'Mandera'
    'KE25' => 'Marsabit County',            // Changed from 'Marsabit'
    'KE26' => 'Meru County',                // Changed from 'Meru'
    'KE27' => 'Migori County',              // Changed from 'Migori'
    'KE28' => 'Mombasa County',             // Changed from 'Mombasa'
    'KE29' => 'Murang\'a County',           // Changed from 'Murang’a'
    'KE30' => 'Nairobi City County',        // Changed from 'Nairobi County'
    'KE31' => 'Nakuru County',              // Changed from 'Nakuru'
    'KE32' => 'Nandi County',               // Changed from 'Nandi'
    'KE33' => 'Narok County',               // Changed from 'Narok'
    'KE34' => 'Nyamira County',             // Changed from 'Nyamira'
    'KE35' => 'Nyandarua County',           // Changed from 'Nyandarua'
    'KE36' => 'Nyeri County',               // Changed from 'Nyeri'
    'KE37' => 'Samburu County',             // Changed from 'Samburu'
    'KE38' => 'Siaya County',               // Changed from 'Siaya'
    'KE39' => 'Taita–Taveta County',        // Changed from 'Taita-Taveta'
    'KE40' => 'Tana River County',          // Changed from 'Tana River'
    'KE41' => 'Tharaka-Nithi County',       // Changed from 'Tharaka-Nithi'
    'KE42' => 'Trans-Nzoia County',         // Changed from 'Trans Nzoia'
    'KE43' => 'Turkana County',             // Changed from 'Turkana'
    'KE44' => 'Uasin Gishu County',         // Changed from 'Uasin Gishu'
    'KE45' => 'Vihiga County',              // Changed from 'Vihiga'
    'KE46' => 'Wajir County',               // Changed from 'Wajir'
    'KE47' => 'West Pokot County',          // Changed from 'West Pokot'
),
'LR' => array( // Liberian provinces.
    'BM' => 'Bomi',
    'BN' => 'Bong',
    'GA' => '',          // Missing in Mautic, left unchanged
    'GB' => 'Grand Basaa',       // Changed from 'Grand Bassa'
    'GC' => 'Grand Cape Mount',
    'GG' => 'Grand Gedeh',
    'GK' => 'Grand Kru',
    'LO' => 'Lofa',
    'MA' => 'Margibi',
    'MY' => 'Maryland',
    'MO' => 'Montserrado',
    'NM' => 'Nimba',
    'RV' => 'Rivercess',
    'RG' => '',         // Missing in Mautic, left unchanged
    'SN' => 'Sinoe'
),
'MD' => array( // Moldovan states.
    'C'  => 'Chisinau',
    'BL' => 'Balti',
    'AN' => '',   // Missing in Mautic, value removed
    'BS' => '',   // Missing in Mautic, value removed
    'BR' => '',   // Missing in Mautic, value removed
    'CH' => 'Cahul',
    'CT' => '',   // Missing in Mautic, value removed
    'CL' => '',   // Missing in Mautic, value removed
    'CS' => '',   // Missing in Mautic, value removed
    'CM' => '',   // Missing in Mautic, value removed
    'CR' => '',   // Missing in Mautic, value removed
    'DN' => '',   // Missing in Mautic, value removed
    'DR' => '',   // Missing in Mautic, value removed
    'DB' => '',   // Missing in Mautic, value removed
    'ED' => 'Edinet',
    'FL' => '',   // Missing in Mautic, value removed
    'FR' => '',   // Missing in Mautic, value removed
    'GE' => 'Gagauzia, Unitate Teritoriala Autonoma',
    'GL' => '',   // Missing in Mautic, value removed
    'HN' => '',   // Missing in Mautic, value removed
    'IL' => '',   // Missing in Mautic, value removed
    'LV' => '',   // Missing in Mautic, value removed
    'NS' => '',   // Missing in Mautic, value removed
    'OC' => '',   // Missing in Mautic, value removed
    'OR' => 'Orhei',
    'RZ' => '',   // Missing in Mautic, value removed
    'RS' => '',   // Missing in Mautic, value removed
    'SG' => '',   // Missing in Mautic, value removed
    'SR' => 'Soroca',
    'ST' => '',   // Missing in Mautic, value removed
    'SD' => '',   // Missing in Mautic, value removed
    'SV' => '',   // Missing in Mautic, value removed
    'TR' => 'Taraclia',
    'TL' => '',   // Missing in Mautic, value removed
    'UN' => 'Ungheni',
),
'MX' => array( // Mexican states.
    'DF' => 'Ciudad de México',
    'JA' => 'Jalisco',
    'NL' => 'Nuevo León',
    'AG' => 'Aguascalientes',
    'BC' => 'Baja California',
    'BS' => 'Baja California Sur',
    'CM' => 'Campeche',
    'CS' => 'Chiapas',
    'CH' => 'Chihuahua',
    'CO' => 'Coahuila',
    'CL' => 'Colima',
    'DG' => 'Durango',
    'GT' => 'Guanajuato',
    'GR' => 'Guerrero',
    'HG' => 'Hidalgo',
    'MX' => 'Estado de México',
    'MI' => 'Michoacán',
    'MO' => 'Morelos',
    'NA' => 'Nayarit',
    'OA' => 'Oaxaca',
    'PU' => 'Puebla',
    'QT' => 'Querétaro',
    'QR' => 'Quintana Roo',
    'SL' => 'San Luis Potosí',
    'SI' => 'Sinaloa',
    'SO' => 'Sonora',
    'TB' => 'Tabasco',
    'TM' => 'Tamaulipas',
    'TL' => 'Tlaxcala',
    'VE' => 'Veracruz',
    'YU' => 'Yucatán',
    'ZA' => 'Zacatecas',
),
'MY' => array( // Malaysian states.
    'JHR' => 'Johor',
    'KDH' => 'Kedah',
    'KTN' => 'Kelantan',
    'LBN' => 'Wilayah Persekutuan Labuan', // Changed from 'Labuan'
    'MLK' => 'Melaka', // Changed from 'Malacca (Melaka)'
    'NSN' => 'Negeri Sembilan',
    'PHG' => 'Pahang',
    'PNG' => 'Pulau Pinang', // Changed from 'Penang (Pulau Pinang)'
    'PRK' => 'Perak',
    'PLS' => 'Perlis',
    'SBH' => 'Sabah',
    'SWK' => 'Sarawak',
    'SGR' => 'Selangor',
    'TRG' => 'Terengganu',
    'PJY' => 'Wilayah Persekutuan Putrajaya', // Changed from 'Putrajaya'
    'KUL' => 'Wilayah Persekutuan Kuala Lumpur', // Changed from 'Kuala Lumpur'
),
'MZ' => array( // Mozambican provinces.
    'MZP'   => 'Cabo Delgado',
    'MZG'   => '', // Gaza is missing in Mautic, left blank
    'MZI'   => 'Inhambane',
    'MZB'   => 'Manica',
    'MZL'   => 'Maputo', // Changed to 'Maputo'
    'MZMPM' => 'Maputo',
    'MZN'   => 'Numpula', // Changed from 'Nampula' to 'Numpula'
    'MZA'   => 'Niaaea', // Changed from 'Niassa' to 'Niaaea'
    'MZS'   => 'Sofala',
    'MZT'   => 'Tete',
    'MZQ'   => 'Zambezia', // Changed from 'Zambézia' to 'Zambezia'
),
'NG' => array( // Nigerian provinces.
    'AB' => 'Abia',
    'FC' => 'Abuja Capital Territory', // Changed from 'Abuja' to 'Abuja Capital Territory'
    'AD' => 'Adamawa',
    'AK' => 'Akwa Ibom',
    'AN' => 'Anambra',
    'BA' => 'Bauchi',
    'BY' => 'Bayelsa',
    'BE' => 'Benue',
    'BO' => 'Borno',
    'CR' => 'Cross River',
    'DE' => 'Delta',
    'EB' => 'Ebonyi',
    'ED' => 'Edo',
    'EK' => 'Ekiti',
    'EN' => 'Enugu',
    'GO' => 'Gombe',
    'IM' => 'Imo',
    'JI' => 'Jigawa',
    'KD' => 'Kaduna',
    'KN' => 'Kano',
    'KT' => 'Katsina',
    'KE' => 'Kebbi',
    'KO' => 'Kogi',
    'KW' => 'Kwara',
    'LA' => 'Lagos',
    'NA' => 'Nassarawa', // Changed from 'Nasarawa' to 'Nassarawa'
    'NI' => 'Niger',
    'OG' => 'Ogun',
    'ON' => 'Ondo',
    'OS' => 'Osun',
    'OY' => 'Oyo',
    'PL' => '', // Missing in Mautic, left blank
    'RI' => 'Rivers',
    'SO' => 'Sokoto',
    'TA' => 'Taraba',
    'YO' => 'Yobe',
    'ZA' => 'Zamfara',
),
'NP' => array( // Nepalese zones. Does not exist in Mautic
    'BAG' => 'Bagmati',
    'BHE' => 'Bheri',
    'DHA' => 'Dhaulagiri',
    'GAN' => 'Gandaki',
    'JAN' => 'Janakpur',
    'KAR' => 'Karnali',
    'KOS' => 'Koshi',
    'LUM' => 'Lumbini',
    'MAH' => 'Mahakali',
    'MEC' => 'Mechi',
    'NAR' => 'Narayani',
    'RAP' => 'Rapti',
    'SAG' => 'Sagarmatha',
    'SET' => 'Seti',
),
'NI' => array( // Nicaraguan states.
    'NI-AN' => 'Atlantico Norte', // Changed from 'Atlántico Norte' to 'Atlantico Norte'
    'NI-AS' => 'Atlantico Sur',   // Changed from 'Atlántico Sur' to 'Atlantico Sur'
    'NI-BO' => 'Boaco',
    'NI-CA' => 'Carazo',
    'NI-CI' => 'Chinandega',
    'NI-CO' => 'Chontales',
    'NI-ES' => 'Esteli',          // Changed from 'Estelí' to 'Esteli'
    'NI-GR' => '',         // Missing in Mautic, left blank
    'NI-JI' => 'Jinotega',
    'NI-LE' => 'Leon',            // Changed from 'León' to 'Leon'
    'NI-MD' => 'Madriz',
    'NI-MN' => 'Managua',
    'NI-MS' => 'Masaya',
    'NI-MT' => 'Matagalpa',
    'NI-NS' => 'Nueva Segovia',
    'NI-RI' => 'Rivas',
    'NI-SJ' => 'Rio San Juan',    // Changed from 'Río San Juan' to 'Rio San Juan'
),
'NZ' => array( // New Zealand states.
    'NTL' => 'Northland',
    'AUK' => 'Auckland',
    'WKO' => 'waikato',            // Changed from 'Waikato' to 'waikato'
    'BOP' => 'Bay of Plenty',
    'TKI' => 'Taranaki',
    'GIS' => 'Gisborne',
    'HKB' => 'Hawkes Bay',         // Changed from 'Hawke’s Bay' to 'Hawkes Bay'
    'MWT' => 'Manawatu-Wanganui',
    'WGN' => 'Wellington',
    'NSN' => 'Nelson',
    'MBH' => 'Marlborough',
    'TAS' => 'Tasman',
    'WTC' => 'West Coast',
    'CAN' => 'Canterbury',
    'OTA' => 'Otago',
    'STL' => 'Southland',
),
'PA' => array( // Panamanian states.
    'PA-1'  => 'Bocas del Toro',
    'PA-2'  => 'Cocle',               // Changed from 'Coclé' to 'Cocle'
    'PA-3'  => 'Chiriqui',            // Changed from 'Chiriquí' to 'Chiriqui'
    'PA-5'  => 'Darien',              // Changed from 'Darién' to 'Darien'
    'PA-6'  => 'Herrera',
    'PA-7'  => 'Loa Santoa',          // Changed from 'Los Santos' to 'Loa Santoa'
    'PA-8'  => 'Panama',              // Changed from 'Panamá' to 'Panama'
    'PA-9'  => 'Veraguas',
    'PA-4' => 'Chiriqui',
    'PA-10' => '',
    'PA-EM' => '',
    'PA-KY' => '',
    'PA-NB' => '',
),
'PE' => array( // Peruvian states.
    'CAL' => 'El Callao',
    'ANC' => 'Ancash',            // Changed from 'Ancash' to 'Ancash'
    'APU' => 'Apurimac',          // Changed from 'Apurímac' to 'Apurimac'
    'ARE' => 'Arequipa',
    'AYA' => 'Ayacucho',
    'CAJ' => 'Cajamarca',
    'CUS' => 'Cuzco',             // Changed from 'Cusco' to 'Cuzco'
    'HUV' => 'Huancavelica',
    'HUC' => 'Huanuco',           // Changed from 'Huánuco' to 'Huanuco'
    'ICA' => 'Ica',
    'JUN' => 'Junin',             // Changed from 'Junín' to 'Junin'
    'LAL' => 'La Libertad',
    'LAM' => 'Lambayeque',
    'LIM' => 'Lima',
    'LOR' => 'Loreto',
    'MDD' => 'Madre de Dios',
    'MOQ' => 'Moquegua',
    'PAS' => 'Pasco',
    'PIU' => 'Piura',
    'PUN' => 'Puno',
    'SAM' => 'San Martin',        // Changed from 'San Martín' to 'San Martin'
    'TAC' => 'Tacna',
    'TUM' => 'Tumbes',
    'UCA' => 'Ucayali',
    'LMA' => 'Lima',
),
'PH' => array( // Philippine provinces.
    'ABR' => 'Abra',
    'AGN' => 'Agusan del Norte',
    'AGS' => 'Agusan del Sur',
    'AKL' => 'Aklan',
    'ALB' => 'Albay',
    'ANT' => 'Antique',
    'APA' => 'Apayao',
    'AUR' => 'Aurora',
    'BAS' => 'Basilan',
    'BAN' => 'Bataan',               // Changed from 'Batasn' to 'Bataan'
    'BTN' => 'Batanes',
    'BTG' => 'Batangas',
    'BEN' => 'Benguet',
    'BIL' => 'Biliran',
    'BOH' => 'Bohol',
    'BUK' => 'Bukidnon',
    'BUL' => 'Bulacan',
    'CAG' => 'Cagayan',
    'CAN' => 'Camarines Norte',
    'CAS' => 'Camarines Sur',
    'CAM' => 'Camiguin',
    'CAP' => 'Capiz',
    'CAT' => 'Catanduanes',
    'CAV' => 'Cavite',
    'CEB' => 'Cebu',
    'COM' => 'Compostela Valley',
    'NCO' => 'North Cotabato',       // Changed from 'Cotabato' to 'North Cotabato'
    'DAV' => 'Davao',                // Changed from 'Davao del Norte' to 'Davao'
    'DAS' => 'Davao del Sur',
    'DAC' => '',                     // 'Davao Occidental' not in Mautic, leave blank
    'DAO' => 'Davao Oriental',
    'DIN' => 'Dinagat Islands',      // Not in Mautic, leave as is
    'EAS' => 'Eastern Samar',
    'GUI' => 'Guimaras',
    'IFU' => 'Ifugao',
    'ILN' => 'Ilocos Norte',
    'ILS' => 'Ilocos Sur',
    'ILI' => 'Iloilo',
    'ISA' => 'Isabela',
    'KAL' => 'Kalinga-Apayso',       // Changed from 'Kalinga' to 'Kalinga-Apayso'
    'LUN' => 'La Union',
    'LAG' => 'Laguna',
    'LAN' => 'Lanao del Norte',
    'LAS' => 'Lanao del Sur',
    'LEY' => 'Leyte',
    'MAG' => 'Maguindanao',
    'MAD' => 'Marinduque',
    'MAS' => 'Masbate',
    'MSC' => 'Misamis Occidental',
    'MSR' => 'Misamis Oriental',
    'MOU' => 'Mountain Province',
    'NEC' => 'Negroe Occidental',    // Changed from 'Negros Occidental' to 'Negroe Occidental'
    'NER' => 'Negros Oriental',
    'NSA' => 'Northern Samar',
    'NUE' => 'Nueva Ecija',
    'NUV' => 'Nueva Vizcaya',
    'MDC' => 'Mindoro Occidental',   // Changed from 'Occidental Mindoro' to 'Mindoro Occidental'
    'MDR' => 'Mindoro Oriental',     // Changed from 'Oriental Mindoro' to 'Mindoro Oriental'
    'PLW' => 'Palawan',
    'PAM' => 'Pampanga',
    'PAN' => 'Pangasinan',
    'QUE' => 'Quezon',
    'QUI' => 'Quirino',
    'RIZ' => 'Rizal',
    'ROM' => 'Romblon',
    'WSA' => 'Western Samar',        // Changed from 'Samar' to 'Western Samar'
    'SAR' => 'Sarangani',
    'SIQ' => 'Siquijor',
    'SOR' => 'Sorsogon',
    'SCO' => 'South Cotabato',
    'SLE' => 'Southern Leyte',
    'SUK' => 'Sultan Kudarat',
    'SLU' => 'Sulu',
    'SUN' => 'Surigao del Norte',
    'SUR' => 'Surigao del Sur',
    'TAR' => 'Tarlac',
    'TAW' => 'Tawi-Tawi',
    'ZMB' => 'Zambales',
    'ZAN' => 'Zamboanga del Norte',
    'ZAS' => 'Zamboanga del Sur',
    'ZSI' => 'Zamboanga Sibiguey',   // Changed from 'Zamboanga Sibugay' to 'Zamboanga Sibiguey'
    '00'  => '',         // Not in Mautic, leave as is
),
'PK' => array( // Pakistani states.
    'JK' => 'Azad Rashmir',             // Changed from 'Azad Kashmir' to 'Azad Rashmir'
    'BA' => 'Baluchistan (en)',         // Changed from 'Balochistan' to 'Baluchistan (en)'
    'TA' => 'Federally Administered Tribal Aresa', // Changed from 'FATA' to 'Federally Administered Tribal Aresa'
    'GB' => '',                         // 'Gilgit Baltistan' not in Mautic, leave blank
    'IS' => 'Islamabad',                // Changed from 'Islamabad Capital Territory' to 'Islamabad'
    'KP' => 'North-West Frontier',      // Changed from 'Khyber Pakhtunkhwa' to 'North-West Frontier'
    'PB' => '',                         // 'Punjab' not in Mautic, leave blank
    'SD' => 'Sind (en)',                // Changed from 'Sindh' to 'Sind (en)'
),
'PY' => array( // Paraguayan states.
    'PY-ASU' => 'Asuncion',           // Changed from 'Asunción' to 'Asuncion'
    'PY-1'   => 'Concepcion',         // Changed from 'Concepción' to 'Concepcion'
    'PY-2'   => 'San Pedro',          // No change needed
    'PY-3'   => 'Cordillera',         // No change needed
    'PY-4'   => 'Guaira',             // Changed from 'Guairá' to 'Guaira'
    'PY-5'   => 'Caeguazu',           // Changed from 'Caaguazú' to 'Caeguazu'
    'PY-6'   => 'Caazapl',            // Changed from 'Caazapá' to 'Caazapl'
    'PY-7'   => 'Itapua',             // Changed from 'Itapúa' to 'Itapua'
    'PY-8'   => 'Miaiones',           // Changed from 'Misiones' to 'Miaiones'
    'PY-9'   => 'Paraguari',          // Changed from 'Paraguarí' to 'Paraguari'
    'PY-10'  => 'Alto Parana',        // Changed from 'Alto Paraná' to 'Alto Parana'
    'PY-11'  => 'Central',            // No change needed
    'PY-12'  => 'Neembucu',           // Changed from 'Ñeembucú' to 'Neembucu'
    'PY-13'  => 'Amambay',            // No change needed
    'PY-14'  => 'Canindeyu',          // No change needed
    'PY-15'  => 'Presidente Hayes',   // No change needed
    'PY-16'  => 'Alto Paraguay',      // No change needed
    'PY-17'  => 'Boqueron',           // Changed from 'Boquerón' to 'Boqueron'
),
'RO' => array( // Romanian states.
    'AB' => 'Alba',                // No change needed
    'AR' => 'Arad',                // No change needed
    'AG' => 'Arges',               // Changed from 'Argeș' to 'Arges'
    'BC' => 'Bacau',               // Changed from 'Bacău' to 'Bacau'
    'BH' => 'Bihor',               // No change needed
    'BN' => 'Bistrita-Nasaud',     // Changed from 'Bistrița-Năsăud' to 'Bistrita-Nasaud'
    'BT' => "Boto'ani",            // Changed from 'Botoșani' to 'Boto'ani'
    'BR' => 'Braila',              // Changed from 'Brăila' to 'Braila'
    'BV' => "Bra'ov",              // Changed from 'Brașov' to 'Bra'ov'
    'B'  => 'Bucuresti',           // Changed from 'București' to 'Bucuresti'
    'BZ' => 'Buzau',               // Changed from 'Buzău' to 'Buzau'
    'CL' => 'Ca la ras\'i',        // Changed from 'Călărași' to 'Ca la ras\'i'
    'CS' => 'Caras-Severin',       // Changed from 'Caraș-Severin' to 'Caras-Severin'
    'CJ' => 'Cluj',                // No change needed
    'CT' => 'Constant\'a',         // Changed from 'Constanța' to 'Constant\'a'
    'CV' => 'Covasna',             // No change needed
    'DB' => 'Dambovit\'a',         // Changed from 'Dâmbovița' to 'Dambovit\'a'
    'DJ' => 'Dolj',                // No change needed
    'GL' => 'Galat\'i',            // Changed from 'Galați' to 'Galat\'i'
    'GR' => 'Giurgiu',             // No change needed
    'GJ' => 'Gorj',                // No change needed
    'HR' => 'Harghita',            // No change needed
    'HD' => 'Hunedoara',           // No change needed
    'IL' => 'Ialomit\'a',          // Changed from 'Ialomița' to 'Ialomit\'a'
    'IS' => 'Ias\'i',              // Changed from 'Iași' to 'Ias\'i'
    'IF' => 'Ilfov',               // No change needed
    'MM' => 'Maramures',           // Changed from 'Maramureș' to 'Maramures'
    'MH' => 'Mehedint\'i',         // Changed from 'Mehedinți' to 'Mehedint\'i'
    'MS' => 'Mures',               // Changed from 'Mureș' to 'Mures'
    'NT' => 'Neamt',               // Changed from 'Neamț' to 'Neamt'
    'OT' => 'Olt',                 // No change needed
    'PH' => 'Prahova',             // No change needed
    'SJ' => 'Sa laj',              // Changed from 'Sălaj' to 'Sa laj'
    'SM' => 'Satu Mare',           // No change needed
    'SB' => 'Sibiu',               // No change needed
    'SV' => 'Suceava',             // No change needed
    'TR' => 'Teleorman',           // No change needed
    'TM' => 'Timis',               // Changed from 'Timiș' to 'Timis'
    'TL' => 'Tulcea',              // No change needed
    'VL' => 'Valcea',              // Changed from 'Vâlcea' to 'Valcea'
    'VS' => 'Vaslui',              // No change needed
    'VN' => 'Vrancea',             // No change needed
),
'SN' => array( // Regions of Senegal. Ref: https://github.com/unicode-org/cldr/blob/release-42/common/subdivisions/en.xml#L4801.
    'SNDB' => 'Diourbel',           // No change needed
    'SNDK' => 'Dakar',              // No change needed
    'SNFK' => 'Fatick',             // No change needed
    'SNKA' => '',                   // 'Kaffrine' not in Mautic, left blank
    'SNKD' => 'Kolda',              // No change needed
    'SNKE' => '',                   // 'Kédougou' not in Mautic, left blank
    'SNKL' => 'Kaolack',            // No change needed
    'SNLG' => 'Louga',              // No change needed
    'SNMT' => 'Matam',              // No change needed
    'SNSE' => '',                   // 'Sédhiou' not in Mautic, left blank
    'SNSL' => 'Saint-Louis',        // No change needed
    'SNTC' => 'Tambacounda',        // No change needed
    'SNTH' => 'Thies',              // Changed from 'Thiès' to 'Thies'
    'SNZG' => 'Ziguinchor',         // No change needed
),
'SV' => array( // Salvadoran states.
    'SV-AH' => 'Ahuachapan',        // Changed from 'Ahuachapán' to 'Ahuachapan'
    'SV-CA' => 'Cabanas',           // Changed from 'Cabañas' to 'Cabanas'
    'SV-CH' => 'Chalatenango',      // No change needed
    'SV-CU' => 'Cuscatlan',         // Changed from 'Cuscatlán' to 'Cuscatlan'
    'SV-LI' => '',                  // 'La Libertad' not in Mautic, left blank
    'SV-MO' => 'Morazan',           // Changed from 'Morazán' to 'Morazan'
    'SV-PA' => '',                  // 'La Paz' not in Mautic, left blank
    'SV-SA' => 'Santa Ana',         // No change needed
    'SV-SM' => 'San Miguel',        // No change needed
    'SV-SO' => 'Sonsonate',         // No change needed
    'SV-SS' => 'San Salvador',      // No change needed
    'SV-SV' => 'San Vicente',       // No change needed
    'SV-UN' => '',                  // 'La Unión' not in Mautic, left blank
    'SV-US' => 'Usulutan',          // Changed from 'Usulután' to 'Usulutan'
),
'TH' => array( // Thai states.
    'TH-37' => 'Amnat Charoen',                // No change needed
    'TH-15' => 'Ang Thong',                    // No change needed
    'TH-14' => 'Phra Nakhon Si Ayutthaya',     // Changed from 'Ayutthaya' to 'Phra Nakhon Si Ayutthaya'
    'TH-10' => 'Krung Thep Maha Nakhon Bangkok', // Changed from 'Bangkok' to 'Krung Thep Maha Nakhon Bangkok'
    'TH-38' => '',                             // 'Bueng Kan' not in Mautic, left blank
    'TH-31' => 'Buri Ram',                     // No change needed
    'TH-24' => 'Chachoengsao',                 // No change needed
    'TH-18' => 'Chai Nat',                     // No change needed
    'TH-36' => 'Chaiyaphum',                   // No change needed
    'TH-22' => 'Chanthaburi',                  // No change needed
    'TH-50' => 'Chiang Mai',                   // No change needed
    'TH-57' => 'Chiang Rai',                   // No change needed
    'TH-20' => 'Chon Buri',                    // Changed from 'Chonburi' to 'Chon Buri'
    'TH-86' => 'Chumphon',                     // No change needed
    'TH-46' => 'Kalasin',                      // No change needed
    'TH-62' => 'Kamphaeng Phet',               // Changed from 'Kamphaeng Phet' to 'Kamphasng Phet'
    'TH-71' => 'Kanchanaburi',                 // No change needed
    'TH-40' => 'Khon Kaen',                    // No change needed
    'TH-81' => 'Krabi',                        // No change needed
    'TH-52' => 'Lampang',                      // No change needed
    'TH-51' => 'Lamphun',                      // No change needed
    'TH-42' => 'Loei',                         // No change needed
    'TH-16' => 'Lop Buri',                     // Changed from 'Lopburi' to 'Lop Buri'
    'TH-58' => 'Mae Hong Son',                 // No change needed
    'TH-44' => 'Maha Sarakham',                // No change needed
    'TH-49' => 'Mukdahan',                     // No change needed
    'TH-26' => 'Nakhon Nayok',                 // No change needed
    'TH-73' => 'Nakhon Pathom',                // No change needed
    'TH-48' => 'Nakhon Phanom',                // No change needed
    'TH-30' => 'Nakhon Ratchasima',            // No change needed
    'TH-60' => 'Nakhon Sawan',                 // No change needed
    'TH-80' => 'Nakhon Si Thammarat',          // No change needed
    'TH-55' => 'Nan',                          // No change needed
    'TH-96' => 'Narathiwat',                   // No change needed
    'TH-39' => 'Nong Bua Lam Phu',             // No change needed
    'TH-43' => 'Nong Khai',                    // No change needed
    'TH-12' => 'Nonthaburi',                   // No change needed
    'TH-13' => 'Pathum Thani',                 // No change needed
    'TH-94' => 'Pattani',                      // No change needed
    'TH-82' => 'Phangnga',                     // Changed from 'Phang Nga' to 'Phangnga'
    'TH-93' => 'Phatthalung',                  // No change needed
    'TH-56' => 'Phayao',                       // No change needed
    'TH-67' => 'Phetchabun',                   // No change needed
    'TH-76' => 'Phetchaburi',                  // No change needed
    'TH-66' => 'Phichit',                      // No change needed
    'TH-65' => 'Phitsanulok',                  // No change needed
    'TH-54' => 'Phrae',                        // No change needed
    'TH-83' => 'Phaket',                       // Changed from 'Phuket' to 'Phaket'
    'TH-25' => 'Prachin Buri',                 // No change needed
    'TH-77' => 'Prachuap Khiri Khan',          // No change needed
    'TH-85' => 'Ranong',                       // No change needed
    'TH-70' => 'Ratchaburi',                   // No change needed
    'TH-21' => 'Rayong',                       // No change needed
    'TH-45' => 'Roi Et',                       // No change needed
    'TH-27' => 'Sa Kaeo',                      // No change needed
    'TH-47' => 'Sakon Nakhon',                 // No change needed
    'TH-11' => 'Samut Prakan',                 // No change needed
    'TH-74' => 'Samut Sakhon',                 // No change needed
    'TH-75' => 'Samut Songkhram',              // No change needed
    'TH-19' => 'Saraburi',                     // No change needed
    'TH-91' => 'Satun',                        // No change needed
    'TH-17' => 'Sing Buri',                    // No change needed
    'TH-33' => 'Si Sa Ket',                    // Changed from 'Sisaket' to 'Si Sa Ket'
    'TH-90' => 'Songkhla',                     // No change needed
    'TH-64' => 'Sukhothai',                    // No change needed
    'TH-72' => 'Suphan Buri',                  // No change needed
    'TH-84' => 'Surat Thani',                  // No change needed
    'TH-32' => 'Surin',                        // No change needed
    'TH-63' => 'Tak',                          // No change needed
    'TH-92' => 'Trang',                        // No change needed
    'TH-23' => 'Trat',                         // No change needed
    'TH-34' => 'Ubon Ratchathani',             // No change needed
    'TH-41' => 'Udon Thani',                   // No change needed
    'TH-61' => 'Uthai Thani',                  // No change needed
    'TH-53' => 'Uttaradit',                    // No change needed
    'TH-95' => 'Yala',                         // No change needed
    'TH-35' => 'Yasothon',                     // No change needed
),
'TR' => array( // Turkish states.
    'TR01' => 'Adana',                         // No change needed
    'TR02' => 'Ad yaman',                      // Changed from 'Adıyaman' to 'Ad yaman'
    'TR03' => 'Afyon',                         // No change needed
    'TR04' => 'Ag r',                          // Changed from 'Ağrı' to 'Ag r'
    'TR05' => 'Amasya',                        // No change needed
    'TR06' => 'Ankara',                        // No change needed
    'TR07' => 'Antalya',                       // No change needed
    'TR08' => 'Artvin',                        // No change needed
    'TR09' => 'Aydin',                         // Changed from 'Aydın' to 'Aydin'
    'TR10' => 'Bal kesir',                     // Changed from 'Balıkesir' to 'Bal kesir'
    'TR11' => 'Bilecik',                       // No change needed
    'TR12' => 'Bingol',                        // Changed from 'Bingöl' to 'Bingol'
    'TR13' => 'Bitlis',                        // No change needed
    'TR14' => 'Bolu',                          // No change needed
    'TR15' => 'Burdur',                        // No change needed
    'TR16' => 'Bursa',                         // No change needed
    'TR17' => 'Canakkale',                     // Changed from 'Çanakkale' to 'Canakkale'
    'TR18' => 'Cankir',                        // Changed from 'Çankırı' to 'Cankir'
    'TR19' => 'Corum',                         // Changed from 'Çorum' to 'Corum'
    'TR20' => 'Denizli',                       // No change needed
    'TR21' => 'Diyarbakir',                    // Changed from 'Diyarbakır' to 'Diyarbakir'
    'TR22' => 'Edirne',                        // No change needed
    'TR23' => 'Elazig',                        // Changed from 'Elazığ' to 'Elazig'
    'TR24' => 'Erzincan',                      // No change needed
    'TR25' => 'Erzurum',                       // No change needed
    'TR26' => 'Eskis\'ehir',                   // Changed from 'Eskişehir' to 'Eskis\'ehir'
    'TR27' => 'Gaziantep',                     // No change needed
    'TR28' => 'Giresun',                       // No change needed
    'TR29' => 'Gms\'hane',                     // Changed from 'Gümüşhane' to 'Gms\'hane'
    'TR30' => 'Hakkari',                       // No change needed
    'TR31' => 'Hatay',                         // No change needed
    'TR32' => 'Isparta',                       // No change needed
    'TR33' => 'Icel',                          // Changed from 'İçel' to 'Icel'
    'TR34' => 'Istanbul',                      // Changed from 'İstanbul' to 'Istanbul'
    'TR35' => 'Izmir',                         // Changed from 'İzmir' to 'Izmir'
    'TR36' => 'Kars',                          // No change needed
    'TR37' => 'Kastamonu',                     // No change needed
    'TR38' => 'Kayseri',                       // No change needed
    'TR39' => 'Kirklareli',                    // Changed from 'Kırklareli' to 'Kirklareli'
    'TR40' => 'Kirs\'ehir',                    // Changed from 'Kırşehir' to 'Kirs\'ehir'
    'TR41' => 'Kocaeli',                       // No change needed
    'TR42' => 'Konya',                         // No change needed
    'TR43' => 'Ktahya',                        // Changed from 'Kütahya' to 'Ktahya'
    'TR44' => 'Malatya',                       // No change needed
    'TR45' => 'Manisa',                        // No change needed
    'TR46' => 'Kahramanmaras',                 // Changed from 'Kahramanmaraş' to 'Kahramanmaras'
    'TR47' => 'Mardin',                        // No change needed
    'TR48' => 'Mugila',                        // Changed from 'Muğla' to 'Mugila'
    'TR49' => 'Mus',                           // Changed from 'Muş' to 'Mus'
    'TR50' => 'Nevs\'ehir',                    // Changed from 'Nevşehir' to 'Nevs\'ehir'
    'TR51' => 'Nigide',                        // Changed from 'Niğde' to 'Nigide'
    'TR52' => 'Ordu',                          // No change needed
    'TR53' => 'Rize',                          // No change needed
    'TR54' => 'Sakarya',                       // No change needed
    'TR55' => 'Samsun',                        // No change needed
    'TR56' => 'Siirt',                         // No change needed
    'TR57' => 'Sinop',                         // No change needed
    'TR58' => 'Sivas',                         // No change needed
    'TR59' => 'Tekirdag',                      // Changed from 'Tekirdağ' to 'Tekirdag'
    'TR60' => 'Tokat',                         // No change needed
    'TR61' => 'Trabzon',                       // No change needed
    'TR62' => 'Tunceli',                       // No change needed
    'TR63' => 'S\'anliurfa',                   // Changed from 'Şanlıurfa' to 'S\'anliurfa'
    'TR64' => 'Us\'ak',                        // Changed from 'Uşak' to 'Us\'ak'
    'TR65' => 'Van',                           // No change needed
    'TR66' => 'Yozgat',                        // No change needed
    'TR67' => 'Zonguldak',                     // No change needed
    'TR68' => 'Aksaray',                       // No change needed
    'TR69' => 'Bayburt',                       // No change needed
    'TR70' => 'Karaman',                       // No change needed
    'TR71' => 'Kirikkale',                     // Changed from 'Kırıkkale' to 'Kirikkale'
    'TR72' => 'Batman',                        // No change needed
    'TR73' => 'S\'rnak',                       // Changed from 'Şırnak' to 'S\'rnak'
    'TR74' => 'Bartin',                        // Changed from 'Bartın' to 'Bartin'
    'TR75' => 'Ardahan',                       // No change needed
    'TR76' => 'Igidir',                        // Changed from 'Iğdır' to 'Igidir'
    'TR77' => 'Yalova',                        // No change needed
    'TR78' => 'Karabk',                        // Changed from 'Karabük' to 'Karabk'
    'TR79' => 'Kilis',                         // No change needed
    'TR80' => 'Osmaniye',                      // No change needed
    'TR81' => 'Duzce',                         // Changed from 'Düzce' to 'Duzce'
),
'TZ' => array( // Tanzanian states.
    'TZ01' => 'Arusha',                     // No change needed
    'TZ02' => 'Dar-es-Salaam',              // Changed from 'Dar es Salaam' to 'Dar-es-Salaam'
    'TZ03' => 'Dodoma',                     // No change needed
    'TZ04' => 'Iringa',                     // No change needed
    'TZ05' => 'Kagera',                     // No change needed
    'TZ06' => 'Kaskazini Pemba',            // Changed from 'Pemba North' to 'Kaskazini Pemba'
    'TZ07' => 'Kaskazini Unguja',           // Changed from 'Zanzibar North' to 'Kaskazini Unguja'
    'TZ08' => 'Xigoma',                     // Changed from 'Kigoma' to 'Xigoma'
    'TZ09' => 'Kilimanjaro',                // No change needed
    'TZ10' => 'Rusini Pemba',               // Changed from 'Pemba South' to 'Rusini Pemba'
    'TZ11' => 'Kusini Unguja',              // Changed from 'Zanzibar South' to 'Kusini Unguja'
    'TZ12' => 'Lindi',                      // No change needed
    'TZ13' => 'Mara',                       // No change needed
    'TZ14' => 'Mbeya',                      // No change needed
    'TZ15' => 'Mjini Magharibi',            // Changed from 'Zanzibar West' to 'Mjini Magharibi'
    'TZ16' => 'Morogoro',                   // No change needed
    'TZ17' => 'Mtwara',                     // No change needed
    'TZ18' => '',                     // No exact match found, leaving as is
    'TZ19' => 'Pwani',                      // Changed from 'Coast' to 'Pwani'
    'TZ20' => 'Rukwa',                      // No change needed
    'TZ21' => 'Ruvuma',                     // No change needed
    'TZ22' => 'Shinyanga',                  // No change needed
    'TZ23' => 'Singida',                    // No change needed
    'TZ24' => 'Tabora',                     // No change needed
    'TZ25' => 'Tanga',                      // No change needed
    'TZ26' => 'Manyara',                    // No change needed
    'TZ27' => '',                           // No match in Mautic, leaving blank
    'TZ28' => '',                           // No match in Mautic, leaving blank
    'TZ29' => '',                           // No match in Mautic, leaving blank
    'TZ30' => '',                           // No match in Mautic, leaving blank
),
'RS' => array( // Serbian districts.
    'RS00' => 'Srbija',                // Belgrade
    'RS14' => 'Srbija',                // Bor
    'RS11' => 'Srbija',                // Braničevo
    'RS02' => 'Srbija',                // Central Banat
    'RS10' => 'Srbija',                // Danube
    'RS23' => 'Srbija',                // Jablanica
    'RS09' => 'Srbija',                // Kolubara
    'RS08' => 'Srbija',                // Mačva
    'RS17' => 'Srbija',                // Morava
    'RS20' => 'Srbija',                // Nišava
    'RS01' => 'Vojvodina',             // North Bačka
    'RS03' => 'Vojvodina',             // North Banat
    'RS24' => 'Srbija',                // Pčinja
    'RS22' => 'Srbija',                // Pirot
    'RS13' => 'Srbija',                // Pomoravlje
    'RS19' => 'Srbija',                // Rasina
    'RS18' => 'Srbija',                // Raška
    'RS06' => 'Vojvodina',             // South Bačka
    'RS04' => 'Vojvodina',             // South Banat
    'RS07' => 'Vojvodina',             // Srem
    'RS12' => 'Srbija',                // Šumadija
    'RS21' => 'Srbija',                // Toplica
    'RS05' => 'Vojvodina',             // West Bačka
    'RS15' => 'Srbija',                // Zaječar
    'RS16' => 'Srbija',                // Zlatibor
    'RS25' => 'Kosovo-Metohija',       // Kosovo
    'RS26' => 'Kosovo-Metohija',       // Peć
    'RS27' => 'Kosovo-Metohija',       // Prizren
    'RS28' => 'Kosovo-Metohija',       // Kosovska Mitrovica
    'RS29' => 'Kosovo-Metohija',       // Kosovo-Pomoravlje
    'RSKM' => 'Kosovo-Metohija',       // Kosovo-Metohija
    'RSVO' => 'Vojvodina',             // Vojvodina
),
'UA' => array( // Ukrainian oblasts.
    'UA05' => "Vinnyts'ka Oblast'",    // Changed 'Vinnychchyna' to "Vinnyts'ka Oblast'"
    'UA07' => "Volyos'ka Oblast'",     // Changed 'Volyn' to "Volyos'ka Oblast'"
    'UA09' => "Luhans'ka Oblast'",     // Changed 'Luhanshchyna' to "Luhans'ka Oblast'"
    'UA12' => "Dnipropetrovs'ka Oblast'", // Changed 'Dnipropetrovshchyna' to "Dnipropetrovs'ka Oblast'"
    'UA14' => "Donets'ka Oblast'",     // Changed 'Donechchyna' to "Donets'ka Oblast'"
    'UA18' => "Zhytomyrs'ka Oblast'",  // Changed 'Zhytomyrshchyna' to "Zhytomyrs'ka Oblast'"
    'UA21' => "Zakarpats'ka Oblast'",  // Changed 'Zakarpattia' to "Zakarpats'ka Oblast'"
    'UA23' => "Zaporiz'ka Oblast'",    // Changed 'Zaporizhzhya' to "Zaporiz'ka Oblast'"
    'UA26' => "Ivano-Frankivs'ka Oblast'", // Changed 'Prykarpattia' to "Ivano-Frankivs'ka Oblast'"
    'UA30' => 'Kyiv',                  // No change needed
    'UA32' => "Kyivs'ka Oblast'",      // Changed 'Kyivshchyna' to "Kyivs'ka Oblast'"
    'UA35' => "Kirovohrads'ka Oblast'", // Changed 'Kirovohradschyna' to "Kirovohrads'ka Oblast'"
    'UA40' => 'Sevastopol',            // No change needed
    'UA43' => 'Respublika Krym',       // Changed 'Crimea' to 'Respublika Krym'
    'UA46' => "L'vivs'ka Oblast'",     // Changed 'Lvivshchyna' to "L'vivs'ka Oblast'"
    'UA48' => "Mykolaivs'ka Oblast'",  // Changed 'Mykolayivschyna' to "Mykolaivs'ka Oblast'"
    'UA51' => "Odes 'ka Oblast'",      // Changed 'Odeshchyna' to "Odes 'ka Oblast'"
    'UA53' => "Poltavs'ka Oblast'",    // Changed 'Poltavshchyna' to "Poltavs'ka Oblast'"
    'UA56' => "Rivnens'ka Oblast'",    // Changed 'Rivnenshchyna' to "Rivnens'ka Oblast'"
    'UA59' => "Sums 'ka Oblast'",      // Changed 'Sumshchyna' to "Sums 'ka Oblast'"
    'UA61' => "Ternopil's'ka Oblast'", // Changed 'Ternopilshchyna' to "Ternopil's'ka Oblast'"
    'UA63' => "Kharkivs'ka Oblast'",   // Changed 'Kharkivshchyna' to "Kharkivs'ka Oblast'"
    'UA65' => "Khersons'ka Oblast'",   // Changed 'Khersonshchyna' to "Khersons'ka Oblast'"
    'UA68' => "Khmel'nyts'ka Oblast'", // Changed 'Khmelnychchyna' to "Khmel'nyts'ka Oblast'"
    'UA71' => "Cherkas'ka Oblast'",    // Changed 'Cherkashchyna' to "Cherkas'ka Oblast'"
    'UA74' => "Chernihivs'ka Oblast'", // Changed 'Chernihivshchyna' to "Chernihivs'ka Oblast'"
    'UA77' => "Chernivets'ka Oblast'", // Changed 'Chernivtsi Oblast' to "Chernivets'ka Oblast'"
),
'UG' => array( // Ugandan districts.
    'UG314' => 'Abim',
    'UG301' => 'Adjumani',        // No change needed
    'UG322' => 'Agago',
    'UG323' => 'Alebtong',
    'UG315' => 'Amolatar',
    'UG324' => 'Amudat',
    'UG216' => 'Amuria',
    'UG316' => 'Amuru',
    'UG302' => 'Apac',            // No change needed
    'UG303' => 'Arua',            // No change needed
    'UG217' => 'Budaka',
    'UG218' => 'Bududa',
    'UG201' => 'Bugiri',          // No change needed
    'UG235' => 'Bugweri',
    'UG420' => 'Buhweju',
    'UG117' => 'Buikwe',
    'UG219' => 'Bukedea',
    'UG118' => 'Bukomansimbi',
    'UG220' => 'Bukwa',
    'UG225' => 'Bulambuli',
    'UG416' => 'Buliisa',
    'UG401' => 'Bundibugyo',      // No change needed
    'UG430' => 'Bunyangabu',
    'UG402' => 'Bushenyi',        // No change needed
    'UG202' => 'Busia',           // No change needed
    'UG221' => 'Butaleja',
    'UG119' => 'Butambala',
    'UG233' => 'Butebo',
    'UG120' => 'Buvuma',
    'UG226' => 'Buyende',
    'UG317' => 'Dokolo',
    'UG121' => 'Gomba',
    'UG304' => 'Gulu',            // No change needed
    'UG403' => 'Hoima',           // No change needed
    'UG417' => 'Ibanda',
    'UG203' => 'Iganga',          // No change needed
    'UG418' => 'Isingiro',
    'UG204' => 'Jinja',           // No change needed
    'UG318' => 'Kaabong',
    'UG404' => 'Kabale',          // No change needed
    'UG405' => 'Kabarole',        // No change needed
    'UG213' => 'Kaberamaido',     // No change needed
    'UG427' => 'Kagadi',
    'UG428' => 'Kakumiro',
    'UG101' => 'Kalangala',       // No change needed
    'UG222' => 'Kaliro',
    'UG122' => 'Kalungu',
    'UG102' => 'Kampala',         // No change needed
    'UG205' => 'Kamuli',          // No change needed
    'UG413' => 'Kamwenge',        // No change needed
    'UG414' => 'Kanungu',         // No change needed
    'UG206' => 'Kapchorwa',       // No change needed
    'UG236' => 'Kapelebyong',
    'UG126' => 'Kasanda',
    'UG406' => 'Kasese',          // No change needed
    'UG207' => 'Katakwi',         // No change needed
    'UG112' => 'Kayunga',         // No change needed
    'UG407' => 'Kibaale',         // No change needed
    'UG103' => 'Kiboga',          // No change needed
    'UG227' => 'Kibuku',
    'UG432' => 'Kikuube',
    'UG419' => 'Kiruhura',
    'UG421' => 'Kiryandongo',
    'UG408' => 'Kisoro',          // No change needed
    'UG305' => 'Kitgum',          // No change needed
    'UG319' => 'Koboko',
    'UG325' => 'Kole',
    'UG306' => 'Kotido',          // No change needed
    'UG208' => 'Kumi',            // No change needed
    'UG333' => 'Kwania',
    'UG228' => 'Kween',
    'UG123' => 'Kyankwanzi',
    'UG422' => 'Kyegegwa',
    'UG415' => 'Kyenjojo',        // No change needed
    'UG125' => 'Kyotera',
    'UG326' => 'Lamwo',
    'UG307' => 'Lira',            // No change needed
    'UG229' => 'Luuka',
    'UG104' => 'Luwero',          // No change needed
    'UG124' => 'Lwengo',
    'UG114' => 'Lyantonde',
    'UG223' => 'Manafwa',
    'UG320' => 'Maracha',
    'UG105' => 'Masaka',          // No change needed
    'UG409' => 'Masindi',         // No change needed
    'UG214' => 'Mayuge',          // No change needed
    'UG209' => 'Mbale',           // No change needed
    'UG410' => 'Mbarara',         // No change needed
    'UG423' => 'Mitooma',
    'UG115' => 'Mityana',
    'UG308' => 'Moroto',          // No change needed
    'UG309' => 'Moyo',            // No change needed
    'UG106' => 'Mpigi',           // No change needed
    'UG107' => 'Mubende',         // No change needed
    'UG108' => 'Mukono',          // No change needed
    'UG334' => 'Nabilatuk',
    'UG311' => 'Nakapiripirit',   // No change needed
    'UG116' => 'Nakaseke',
    'UG109' => 'Nakasongola',     // No change needed
    'UG230' => 'Namayingo',
    'UG234' => 'Namisindwa',
    'UG224' => 'Namutumba',
    'UG327' => 'Napak',
    'UG310' => 'Nebbi',           // No change needed
    'UG231' => 'Ngora',
    'UG424' => 'Ntoroko',
    'UG411' => 'Ntungamo',        // No change needed
    'UG328' => 'Nwoya',
    'UG331' => 'Omoro',
    'UG329' => 'Otuke',
    'UG321' => 'Oyam',
    'UG312' => 'Pader',           // No change needed
    'UG332' => 'Pakwach',
    'UG210' => 'Pallisa',         // No change needed
    'UG110' => 'Rakai',           // No change needed
    'UG429' => 'Rubanda',
    'UG425' => 'Rubirizi',
    'UG431' => 'Rukiga',
    'UG412' => 'Rukungiri',       // No change needed
    'UG111' => 'Sembabule',       // No change needed
    'UG232' => 'Serere',
    'UG426' => 'Sheema',
    'UG215' => 'Sironko',         // No change needed
    'UG211' => 'Soroti',          // No change needed
    'UG212' => 'Tororo',          // No change needed
    'UG113' => 'Wakiso',          // No change needed
    'UG313' => 'Yumbe',           // No change needed
    'UG330' => 'Zombo',
),
'UG' => array(
    'UG301' => 'Adjumani',        // No change needed
    'UG302' => 'Arua',            // No change needed
    'UG201' => 'Bugiri',          // No change needed
    'UG401' => 'Bundibugyo',      // No change needed
    'UG402' => 'Bushenyi',        // No change needed
    'UG202' => 'Busia',           // No change needed
    'UG304' => 'Gulu',            // No change needed
    'UG403' => 'Hoima',           // No change needed
    'UG203' => 'Iganga',          // No change needed
    'UG204' => 'Jinja',           // No change needed
    'UG404' => 'Kabale',          // No change needed
    'UG405' => 'Kabarole',        // No change needed
    'UG213' => 'Kaberamaido',     // No change needed
    'UG101' => 'Kalangala',       // No change needed
    'UG102' => 'Kampala',         // No change needed
    'UG205' => 'Kamuli',          // No change needed
    'UG413' => 'Kamwenge',        // No change needed
    'UG414' => 'Kanungu',         // No change needed
    'UG206' => 'Kapchorwa',       // No change needed
    'UG406' => 'Kasese',          // No change needed
    'UG207' => 'Katakwi',         // No change needed
    'UG112' => 'Kayunga',         // No change needed
    'UG407' => 'Kibaale',         // Change from 'Kibaale' to 'Kibale'
    'UG103' => 'Kiboga',          // No change needed
    'UG408' => 'Kisoro',          // No change needed
    'UG305' => 'Kitgum',          // No change needed
    'UG306' => 'Kotido',          // No change needed
    'UG208' => 'Kumi',            // No change needed
    'UG415' => 'Kyenjojo',        // No change needed
    'UG307' => 'Lira',            // No change needed
    'UG104' => 'Luwero',          // No change needed
    'UG105' => 'Masaka',          // No change needed
    'UG409' => 'Masindi',         // No change needed
    'UG214' => 'Mayuge',          // No change needed
    'UG209' => 'Mbale',           // No change needed
    'UG410' => 'Mbarara',         // No change needed
    'UG308' => 'Moroto',          // No change needed
    'UG309' => 'Moyo',            // No change needed
    'UG106' => 'Mpigi',           // No change needed
    'UG107' => 'Mubende',         // No change needed
    'UG108' => 'Mukono',          // No change needed
    'UG311' => 'Nakapiripirit',   // No change needed
    'UG109' => 'Nakasongola',     // No change needed
    'UG310' => 'Nebbi',           // No change needed
    'UG411' => 'Ntungamo',        // No change needed
    'UG312' => 'Pader',           // No change needed
    'UG210' => 'Pallisa',         // No change needed
    'UG110' => 'Rakai',           // No change needed
    'UG412' => 'Rukungiri',       // No change needed
    'UG111' => 'Sembabule',       // No change needed
    'UG215' => 'Sironko',         // No change needed
    'UG211' => 'Soroti',          // No change needed
    'UG212' => 'Tororo',          // No change needed
    'UG113' => 'Wakiso',          // No change needed
    'UG313' => 'Yumbe',           // No change needed
),
'UM' => array(
    '81' => 'Baker Island',         // No change needed
    '84' => 'Howland Island',       // No change needed
    '86' => 'Jarvis Island',        // No change needed
    '67' => 'Johnston Atoll',       // No change needed
    '89' => 'Kingman Reef',         // No change needed
    '71' => 'Midway Atoll',         // Change from 'Midway Atoll' to 'Midway Islands'
    '76' => 'Navassa Island',       // No change needed
    '95' => 'Palmyra Atoll',        // No change needed
    '79' => 'Wake Island',          // Change from 'Wake Island' to 'Wake Ialand'
),

'US' => array( // U.S. states.
    'AL' => 'Alabama',
    'AK' => 'Alaska',
    'AZ' => 'Arizona',
    'AR' => 'Arkansas',
    'CA' => 'California',
    'CO' => 'Colorado',
    'CT' => 'Connecticut',
    'DE' => 'Delaware',
    'DC' => 'District of Columbia',
    'FL' => 'Florida',
    'GA' => 'Georgia',
    'HI' => 'Hawaii',
    'ID' => 'Idaho',
    'IL' => 'Illinois',
    'IN' => 'Indiana',
    'IA' => 'Iowa',
    'KS' => 'Kansas',
    'KY' => 'Kentucky',
    'LA' => 'Louisiana',
    'ME' => 'Maine',
    'MD' => 'Maryland',
    'MA' => 'Massachusetts',
    'MI' => 'Michigan',
    'MN' => 'Minnesota',
    'MS' => 'Mississippi',
    'MO' => 'Missouri',
    'MT' => 'Montana',
    'NE' => 'Nebraska',
    'NV' => 'Nevada',
    'NH' => 'New Hampshire',
    'NJ' => 'New Jersey',
    'NM' => 'New Mexico',
    'NY' => 'New York',
    'NC' => 'North Carolina',
    'ND' => 'North Dakota',
    'OH' => 'Ohio',
    'OK' => 'Oklahoma',
    'OR' => 'Oregon',
    'PA' => 'Pennsylvania',
    'RI' => 'Rhode Island',
    'SC' => 'South Carolina',
    'SD' => 'South Dakota',
    'TN' => 'Tennessee',
    'TX' => 'Texas',
    'UT' => 'Utah',
    'VT' => 'Vermont',
    'VA' => 'Virginia',
    'WA' => 'Washington',
    'WV' => 'West Virginia',
    'WI' => 'Wisconsin',
    'WY' => 'Wyoming',
    'AA' => 'Armed Forces Americas',
    'AE' => 'Armed Forces Europe',
    'AP' => 'Armed Forces Pacific',
),
'UY' => array(
    'UY-AR' => 'Artigsa',            // Change from 'Artigas' to 'Artigsa'
    'UY-CA' => 'Canelones',          // No change needed
    'UY-CL' => 'Cerro Largo',        // No change needed
    'UY-CO' => 'Colonia',            // No change needed
    'UY-DU' => 'Durazno',            // No change needed
    'UY-FS' => 'Flores',             // No change needed
    'UY-FD' => 'Florida',            // No change needed
    'UY-LA' => 'Lavalleja',          // No change needed
    'UY-MA' => 'Maldonado',          // No change needed
    'UY-MO' => 'Montevideo',         // No change needed
    'UY-PA' => 'Paysandu',           // Change from 'Paysandú' to 'Paysandu'
    'UY-RN' => 'Rivera',             // No change needed
    'UY-RV' => 'Rocha',              // No change needed
    'UY-SA' => 'Salto',              // No change needed
    'UY-SJ' => 'San José',           // No change needed
    'UY-SO' => 'Soriano',            // No change needed
    'UY-TA' => 'Tacuarembo',         // Change from 'Tacuarembó' to 'Tacuarembo'
    'UY-TT' => 'Treinta y Tres',     // No change needed
),
'VE' => array(
    'VE-A' => 'Diatrito Federal',        // Change from 'Capital' to 'Diatrito Federal'
    'VE-B' => 'Anzoategui',              // No change needed
    'VE-C' => 'Apure',                   // No change needed
    'VE-D' => 'Aragua',                  // No change needed
    'VE-E' => 'Barinas',                 // No change needed
    'VE-F' => 'Bolívar',                 // No change needed
    'VE-G' => 'Carabobo',                // No change needed
    'VE-H' => 'Cojedes',                 // No change needed
    'VE-I' => 'Falcon',                  // Change from 'Falcón' to 'Falcon'
    'VE-J' => 'Guarico',                 // Change from 'Guárico' to 'Guarico'
    'VE-K' => 'Lara',                    // No change needed
    'VE-L' => 'Merida',                  // Change from 'Mérida' to 'Merida'
    'VE-M' => 'Miranda',                 // No change needed
    'VE-N' => 'Monagas',                 // No change needed
    'VE-O' => 'Nueva Esparta',           // No change needed
    'VE-P' => 'Portuguesa',              // No change needed
    'VE-R' => 'Sucre',                   // No change needed
    'VE-S' => 'Tachira',                 // Change from 'Táchira' to 'Tachira'
    'VE-T' => 'Trujillo',                // No change needed
    'VE-U' => 'Yaracuy',                 // No change needed
    'VE-V' => 'Zulia',                   // No change needed
    'VE-W' => 'Federal Dependencies',    // Change from 'Federal Dependencies' to 'Dependencias Federales'
    'VE-X' => 'Vargas',                  // Change from 'La Guaira (Vargas)' to 'Vargas'
    'VE-Y' => 'Delta Amacuro',           // No change needed
    'VE-Z' => 'Amazonas',                // No change needed
),
'ZA' => array(
    'EC'  => 'Eastern Cape',       // No change needed
    'FS'  => 'Free State',         // No change needed
    'GP'  => 'Gauteng',            // No change needed
    'KZN' => 'Kwazulu-Natal',      // Change from 'KwaZulu-Natal' to 'Kwazulu-Natal'
    'LP'  => 'Limpopo',            // No change needed
    'MP'  => 'Mpumalanga',         // No change needed
    'NC'  => 'Northern Cape',      // No change needed
    'NW'  => 'North West',         // No change needed
    'WC'  => 'Western Cape',       // No change needed
),
'ZM' => array(
    'ZM-01' => 'Western',           // No change needed
    'ZM-02' => 'Central',           // No change needed
    'ZM-03' => 'Eastern',           // No change needed
    'ZM-04' => 'Luapula',           // No change needed
    'ZM-05' => 'Northern',          // No change needed
    'ZM-06' => 'North-Western',     // No change needed
    'ZM-07' => 'Southern',          // No change needed
    'ZM-08' => 'Copperbelt',        // No change needed
    'ZM-09' => 'Lusaka',            // No change needed
    'ZM-10' => '',                  // Missing in Mautic, left blank
),

);